import { PrismaClient } from '@prisma/client';
import { WCAGLevel, WCAGPrinciple } from '../lib/report-calculations';

const prisma = new PrismaClient();

const wcagCriteria = [
  // Principe 1: Perceivable (Waarneembaar)
  // Guideline 1.1: Tekstalternatieven
  {
    code: '1.1.1',
    titleNl: 'Niet-tekstuele content',
    descriptionNl: 'Geef informatieve afbeeldingen en andere niet-tekstuele content een goed tekstalternatief.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.1',
    guidelineTitleNl: 'Tekstalternatieven',
    guidelineDescriptionNl: 'Lever tekstalternatieven voor alle niet-tekstuele content, zodat die veranderd kan worden in andere vormen die mensen nodig hebben, zoals grote letters, braille, spraak, symbolen of eenvoudigere taal.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/non-text-content.html',
  },

  // Guideline 1.2: Op tijd gebaseerde media
  {
    code: '1.2.1',
    titleNl: 'Louter-geluid en louter-videobeeld (vooraf opgenomen)',
    descriptionNl: 'Zorg voor een alternatief voor video-zonder-geluid (bijv. een animatie) of geluid-zonder-video (bijv. een podcast).',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.2',
    guidelineTitleNl: 'Op tijd gebaseerde media',
    guidelineDescriptionNl: 'Lever alternatieven voor op tijd gebaseerde media.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/audio-only-and-video-only-prerecorded.html',
  },
  {
    code: '1.2.2',
    titleNl: 'Ondertitels voor doven en slechthorenden (vooraf opgenomen)',
    descriptionNl: 'Zorg dat video\'s ondertitels hebben voor alle belangrijke geluiden.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.2',
    guidelineTitleNl: 'Op tijd gebaseerde media',
    guidelineDescriptionNl: 'Lever alternatieven voor op tijd gebaseerde media.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/captions-prerecorded.html',
  },
  {
    code: '1.2.3',
    titleNl: 'Audiodescriptie of media-alternatief (vooraf opgenomen)',
    descriptionNl: 'Zorg dat alle belangrijke visuele informatie in video\'s ook te horen is óf zorg voor een tekstalternatief (bijv. een transcript).',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.2',
    guidelineTitleNl: 'Op tijd gebaseerde media',
    guidelineDescriptionNl: 'Lever alternatieven voor op tijd gebaseerde media.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/audio-description-or-media-alternative-prerecorded.html',
  },
  {
    code: '1.2.4',
    titleNl: 'Ondertitels voor doven en slechthorenden (live)',
    descriptionNl: 'Live video\'s worden voorzien van ondertiteling voor doven en slechthorenden. Let op: Er is een wettelijke uitzondering voor live-video\'s.',
    level: WCAGLevel.AA,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.2',
    guidelineTitleNl: 'Op tijd gebaseerde media',
    guidelineDescriptionNl: 'Lever alternatieven voor op tijd gebaseerde media.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/captions-live.html',
  },
  {
    code: '1.2.5',
    titleNl: 'Audiodescriptie (vooraf opgenomen)',
    descriptionNl: 'Zorg dat alle belangrijke visuele informatie in video\'s ook te horen is.',
    level: WCAGLevel.AA,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.2',
    guidelineTitleNl: 'Op tijd gebaseerde media',
    guidelineDescriptionNl: 'Lever alternatieven voor op tijd gebaseerde media.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/audio-description-prerecorded.html',
  },

  // Guideline 1.3: Aanpasbaar
  {
    code: '1.3.1',
    titleNl: 'Info en relaties',
    descriptionNl: 'Info, structuur en relaties in de content die je kan zien, moet ook in de code voor hulpsoftware beschikbaar zijn.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.3',
    guidelineTitleNl: 'Aanpasbaar',
    guidelineDescriptionNl: 'Creëer content die op verschillende manieren gepresenteerd kan worden (bijvoorbeeld eenvoudiger lay-out) zonder verlies van informatie of structuur.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/info-and-relationships.html',
  },
  {
    code: '1.3.2',
    titleNl: 'Betekenisvolle volgorde',
    descriptionNl: 'Zorg ervoor dat alle content in een \'logische\' volgorde staat en dat hulpsoftware deze ook kan bepalen.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.3',
    guidelineTitleNl: 'Aanpasbaar',
    guidelineDescriptionNl: 'Creëer content die op verschillende manieren gepresenteerd kan worden (bijvoorbeeld eenvoudiger lay-out) zonder verlies van informatie of structuur.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/meaningful-sequence.html',
  },
  {
    code: '1.3.3',
    titleNl: 'Zintuiglijke eigenschappen',
    descriptionNl: 'Verwijs niet naar vorm, locatie, kleur, omvang, orientatie of geluid.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.3',
    guidelineTitleNl: 'Aanpasbaar',
    guidelineDescriptionNl: 'Creëer content die op verschillende manieren gepresenteerd kan worden (bijvoorbeeld eenvoudiger lay-out) zonder verlies van informatie of structuur.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/sensory-characteristics.html',
  },
  {
    code: '1.3.4',
    titleNl: 'Weergavestand',
    descriptionNl: 'Content kan in zowel staand als liggend formaat worden bekeken.',
    level: WCAGLevel.AA,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.3',
    guidelineTitleNl: 'Aanpasbaar',
    guidelineDescriptionNl: 'Creëer content die op verschillende manieren gepresenteerd kan worden (bijvoorbeeld eenvoudiger lay-out) zonder verlies van informatie of structuur.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/orientation.html',
  },
  {
    code: '1.3.5',
    titleNl: 'Identificeer het doel van de input',
    descriptionNl: 'Het doel van formuliervelden voor persoonlijke gegevens (bijv. je naam) moeten door hulpsoftware herkend worden.',
    level: WCAGLevel.AA,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.3',
    guidelineTitleNl: 'Aanpasbaar',
    guidelineDescriptionNl: 'Creëer content die op verschillende manieren gepresenteerd kan worden (bijvoorbeeld eenvoudiger lay-out) zonder verlies van informatie of structuur.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/identify-input-purpose.html',
  },

  // Guideline 1.4: Onderscheidbaar
  {
    code: '1.4.1',
    titleNl: 'Gebruik van kleur',
    descriptionNl: 'Gebruik niet alleen maar kleur om informatie over te brengen, bijvoorbeeld in grafieken, diagrammen en tabellen.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.4',
    guidelineTitleNl: 'Onderscheidbaar',
    guidelineDescriptionNl: 'Maak het voor gebruikers gemakkelijker om content te horen en te zien, waaronder scheiding van voorgrond en achtergrond.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/use-of-color.html',
  },
  {
    code: '1.4.2',
    titleNl: 'Geluidsbediening',
    descriptionNl: 'Als geluid automatisch start en langer dan 3 seconden duurt dan moet er een manier zijn om het te pauzeren. Advies: start geluid niet automatisch.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.4',
    guidelineTitleNl: 'Onderscheidbaar',
    guidelineDescriptionNl: 'Maak het voor gebruikers gemakkelijker om content te horen en te zien, waaronder scheiding van voorgrond en achtergrond.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/audio-control.html',
  },
  {
    code: '1.4.3',
    titleNl: 'Contrast (minimum)',
    descriptionNl: 'Alle teksten moeten voldoende kleurcontrast hebben. Tip: gebruik de Colour Contrast Analyzer om het kleurcontrast te bepalen.',
    level: WCAGLevel.AA,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.4',
    guidelineTitleNl: 'Onderscheidbaar',
    guidelineDescriptionNl: 'Maak het voor gebruikers gemakkelijker om content te horen en te zien, waaronder scheiding van voorgrond en achtergrond.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html',
  },
  {
    code: '1.4.4',
    titleNl: 'Herschalen van tekst',
    descriptionNl: 'Tekst kan tot 200% worden vergroot zonder verlies van content of functionaliteit.',
    level: WCAGLevel.AA,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.4',
    guidelineTitleNl: 'Onderscheidbaar',
    guidelineDescriptionNl: 'Maak het voor gebruikers gemakkelijker om content te horen en te zien, waaronder scheiding van voorgrond en achtergrond.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/resize-text.html',
  },
  {
    code: '1.4.5',
    titleNl: 'Afbeeldingen van tekst',
    descriptionNl: 'Gebruik geen afbeeldingen van tekst, maar maak je tekst op met CSS.',
    level: WCAGLevel.AA,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.4',
    guidelineTitleNl: 'Onderscheidbaar',
    guidelineDescriptionNl: 'Maak het voor gebruikers gemakkelijker om content te horen en te zien, waaronder scheiding van voorgrond en achtergrond.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/images-of-text.html',
  },
  {
    code: '1.4.10',
    titleNl: 'Reflow',
    descriptionNl: 'Je website moet responsive zijn en er mag geen content missen. Voorkom scrollen in twee richtingen.',
    level: WCAGLevel.AA,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.4',
    guidelineTitleNl: 'Onderscheidbaar',
    guidelineDescriptionNl: 'Maak het voor gebruikers gemakkelijker om content te horen en te zien, waaronder scheiding van voorgrond en achtergrond.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/reflow.html',
  },
  {
    code: '1.4.11',
    titleNl: 'Contrast van niet-tekstuele content',
    descriptionNl: 'Niet-tekstuele content op je website heeft voldoende kleurcontrast (3,0:1). Denk bijvoorbeeld aan belangrijke afbeeldingen en formuliervelden.',
    level: WCAGLevel.AA,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.4',
    guidelineTitleNl: 'Onderscheidbaar',
    guidelineDescriptionNl: 'Maak het voor gebruikers gemakkelijker om content te horen en te zien, waaronder scheiding van voorgrond en achtergrond.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/non-text-contrast.html',
  },
  {
    code: '1.4.12',
    titleNl: 'Tekstafstand',
    descriptionNl: 'Tekstafstand kan door gebruiker worden aangepast zonder verlies van content.',
    level: WCAGLevel.AA,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.4',
    guidelineTitleNl: 'Onderscheidbaar',
    guidelineDescriptionNl: 'Maak het voor gebruikers gemakkelijker om content te horen en te zien, waaronder scheiding van voorgrond en achtergrond.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/text-spacing.html',
  },
  {
    code: '1.4.13',
    titleNl: 'Content bij hover of focus',
    descriptionNl: 'Content die verschijnt bij hover of focus is afsluitbaar, blijvend en hoverbaar.',
    level: WCAGLevel.AA,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.4',
    guidelineTitleNl: 'Onderscheidbaar',
    guidelineDescriptionNl: 'Maak het voor gebruikers gemakkelijker om content te horen en te zien, waaronder scheiding van voorgrond en achtergrond.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/content-on-hover-or-focus.html',
  },

  // Principe 2: Operable (Bedienbaar)
  // Guideline 2.1: Toetsenbordtoegankelijk
  {
    code: '2.1.1',
    titleNl: 'Toetsenbord',
    descriptionNl: 'Alle functionaliteit is beschikbaar via een toetsenbord.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.1',
    guidelineTitleNl: 'Toetsenbordtoegankelijk',
    guidelineDescriptionNl: 'Maak alle functionaliteit beschikbaar vanaf een toetsenbord.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/keyboard.html',
  },
  {
    code: '2.1.2',
    titleNl: 'Geen toetsenbordval',
    descriptionNl: 'Zorg dat gebruikers van het toetsenbord niet vastlopen.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.1',
    guidelineTitleNl: 'Toetsenbordtoegankelijk',
    guidelineDescriptionNl: 'Maak alle functionaliteit beschikbaar vanaf een toetsenbord.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/no-keyboard-trap.html',
  },
  {
    code: '2.1.4',
    titleNl: 'Enkel teken sneltoetsen',
    descriptionNl: 'Voorkom het gebruik van sneltoetsen die bestaan uit één teken, zoals hoofdletters, kleine letters, leestekens, cijfers of symbolen.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.1',
    guidelineTitleNl: 'Toetsenbordtoegankelijk',
    guidelineDescriptionNl: 'Maak alle functionaliteit beschikbaar vanaf een toetsenbord.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/character-key-shortcuts.html',
  },

  // Guideline 2.2: Genoeg tijd
  {
    code: '2.2.1',
    titleNl: 'Timing aanpasbaar',
    descriptionNl: 'Tijdslimieten kunnen worden uitgezet, aangepast of verlengd.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.2',
    guidelineTitleNl: 'Genoeg tijd',
    guidelineDescriptionNl: 'Geef gebruikers voldoende tijd om de content te lezen en te gebruiken.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/timing-adjustable.html',
  },
  {
    code: '2.2.2',
    titleNl: 'Pauzeren, stoppen of verbergen',
    descriptionNl: 'Voor alle bewegende of scrollende content moet de mogelijkheid zijn om dit te pauzeren, stoppen of verbergen.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.2',
    guidelineTitleNl: 'Genoeg tijd',
    guidelineDescriptionNl: 'Geef gebruikers voldoende tijd om de content te lezen en te gebruiken.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/pause-stop-hide.html',
  },

  // Guideline 2.3: Toevallen en fysieke reacties
  {
    code: '2.3.1',
    titleNl: 'Drie flitsen of beneden drempelwaarde',
    descriptionNl: 'Het snel flitsen van drie keer of meer per seconde kan foto-epileptische aanvallen veroorzaken en is niet toegestaan.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.3',
    guidelineTitleNl: 'Toevallen en fysieke reacties',
    guidelineDescriptionNl: 'Ontwerp content niet op een manier waarvan bekend is dat die toevallen of fysieke reacties veroorzaakt.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/three-flashes-or-below-threshold.html',
  },

  // Guideline 2.4: Navigeerbaar
  {
    code: '2.4.1',
    titleNl: 'Blokken omzeilen',
    descriptionNl: 'Een mechanisme is beschikbaar om herhalende content over te slaan.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.4',
    guidelineTitleNl: 'Navigeerbaar',
    guidelineDescriptionNl: 'Lever manieren om gebruikers te helpen navigeren, content te vinden en te bepalen waar ze zijn.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/bypass-blocks.html',
  },
  {
    code: '2.4.2',
    titleNl: 'Paginatitel',
    descriptionNl: 'Alle pagina\'s hebben een goede titel die het onderwerp beschrijft.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.4',
    guidelineTitleNl: 'Navigeerbaar',
    guidelineDescriptionNl: 'Lever manieren om gebruikers te helpen navigeren, content te vinden en te bepalen waar ze zijn.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/page-titled.html',
  },
  {
    code: '2.4.3',
    titleNl: 'Focus volgorde',
    descriptionNl: 'Focusvolgorde behoudt betekenis en bedienbaarheid.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.4',
    guidelineTitleNl: 'Navigeerbaar',
    guidelineDescriptionNl: 'Lever manieren om gebruikers te helpen navigeren, content te vinden en te bepalen waar ze zijn.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/focus-order.html',
  },
  {
    code: '2.4.4',
    titleNl: 'Linkdoel (in context)',
    descriptionNl: 'Geef links een duidelijke tekst zodat je weet wat er gebeurt als je er op klikt.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.4',
    guidelineTitleNl: 'Navigeerbaar',
    guidelineDescriptionNl: 'Lever manieren om gebruikers te helpen navigeren, content te vinden en te bepalen waar ze zijn.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/link-purpose-in-context.html',
  },
  {
    code: '2.4.5',
    titleNl: 'Meerdere manieren',
    descriptionNl: 'Er is meer dan één manier om een webpagina binnen een set te vinden.',
    level: WCAGLevel.AA,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.4',
    guidelineTitleNl: 'Navigeerbaar',
    guidelineDescriptionNl: 'Lever manieren om gebruikers te helpen navigeren, content te vinden en te bepalen waar ze zijn.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/multiple-ways.html',
  },
  {
    code: '2.4.6',
    titleNl: 'Koppen en labels',
    descriptionNl: 'Gebruik duidelijke koppen en tekstlabels die het onderwerp of doel beschrijven.',
    level: WCAGLevel.AA,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.4',
    guidelineTitleNl: 'Navigeerbaar',
    guidelineDescriptionNl: 'Lever manieren om gebruikers te helpen navigeren, content te vinden en te bepalen waar ze zijn.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/headings-and-labels.html',
  },
  {
    code: '2.4.7',
    titleNl: 'Focus zichtbaar',
    descriptionNl: 'De toetsenbordfocus indicator is zichtbaar.',
    level: WCAGLevel.AA,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.4',
    guidelineTitleNl: 'Navigeerbaar',
    guidelineDescriptionNl: 'Lever manieren om gebruikers te helpen navigeren, content te vinden en te bepalen waar ze zijn.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/focus-visible.html',
  },
  {
    code: '2.4.11',
    titleNl: 'Focus niet bedekt (minimum)',
    level: WCAGLevel.AA,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.4',
    guidelineTitleNl: 'Navigeerbaar',
    guidelineDescriptionNl: 'Lever manieren om gebruikers te helpen navigeren, content te vinden en te bepalen waar ze zijn.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum.html',
  },

  // Guideline 2.5: Input Modaliteiten
  {
    code: '2.5.1',
    titleNl: 'Aanwijzergebaren',
    descriptionNl: 'Alle functionaliteit die met complexe gebaren werkt, werkt ook met een enkele aanraking.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.5',
    guidelineTitleNl: 'Input Modaliteiten',
    guidelineDescriptionNl: 'Maak het eenvoudiger voor gebruikers om de functionaliteit te bedienen met andere vormen van invoer dan alleen het toetsenbord.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/pointer-gestures.html',
  },
  {
    code: '2.5.2',
    titleNl: 'Aanwijzerannulering',
    descriptionNl: 'Voor functionaliteit die via aanraking werkt, geldt dat de actie pas wordt uitgevoerd bij loslaten.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.5',
    guidelineTitleNl: 'Input Modaliteiten',
    guidelineDescriptionNl: 'Maak het eenvoudiger voor gebruikers om de functionaliteit te bedienen met andere vormen van invoer dan alleen het toetsenbord.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/pointer-cancellation.html',
  },
  {
    code: '2.5.3',
    titleNl: 'Label in naam',
    descriptionNl: 'Van alle interactieve elementen met zichtbare tekst is deze tekst ook beschikbaar in de toegankelijkheidsnaam.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.5',
    guidelineTitleNl: 'Input Modaliteiten',
    guidelineDescriptionNl: 'Maak het eenvoudiger voor gebruikers om de functionaliteit te bedienen met andere vormen van invoer dan alleen het toetsenbord.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/label-in-name.html',
  },
  {
    code: '2.5.4',
    titleNl: 'Bewegingsactivering',
    descriptionNl: 'Functionaliteit die wordt geactiveerd door beweging kan ook met interface componenten worden geactiveerd.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.5',
    guidelineTitleNl: 'Input Modaliteiten',
    guidelineDescriptionNl: 'Maak het eenvoudiger voor gebruikers om de functionaliteit te bedienen met andere vormen van invoer dan alleen het toetsenbord.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/motion-actuation.html',
  },
  {
    code: '2.5.7',
    titleNl: 'Sleepbewegingen',
    level: WCAGLevel.AA,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.5',
    guidelineTitleNl: 'Input Modaliteiten',
    guidelineDescriptionNl: 'Maak het eenvoudiger voor gebruikers om de functionaliteit te bedienen met andere vormen van invoer dan alleen het toetsenbord.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements.html',
  },
  {
    code: '2.5.8',
    titleNl: 'Grootte van het aanwijsgebied (minimum)',
    level: WCAGLevel.AA,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.5',
    guidelineTitleNl: 'Input Modaliteiten',
    guidelineDescriptionNl: 'Maak het eenvoudiger voor gebruikers om de functionaliteit te bedienen met andere vormen van invoer dan alleen het toetsenbord.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html',
  },

  // Principe 3: Understandable (Begrijpbaar)
  // Guideline 3.1: Leesbaar
  {
    code: '3.1.1',
    titleNl: 'Taal van de pagina',
    descriptionNl: 'Hulpsoftware moet de taal van de pagina kunnen bepalen, zodat bijvoorbeeld de juiste stem en intonatie gebruikt kan worden.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Understandable,
    guidelineCode: '3.1',
    guidelineTitleNl: 'Leesbaar',
    guidelineDescriptionNl: 'Maak tekstcontent leesbaar en begrijpelijk.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/language-of-page.html',
  },
  {
    code: '3.1.2',
    titleNl: 'Taal van onderdelen',
    descriptionNl: 'Als de taal van de content wisselt dan moet hulpsoftware deze kunnen bepalen.',
    level: WCAGLevel.AA,
    principle: WCAGPrinciple.Understandable,
    guidelineCode: '3.1',
    guidelineTitleNl: 'Leesbaar',
    guidelineDescriptionNl: 'Maak tekstcontent leesbaar en begrijpelijk.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/language-of-parts.html',
  },

  // Guideline 3.2: Voorspelbaar
  {
    code: '3.2.1',
    titleNl: 'Bij focus',
    descriptionNl: 'Focus ontvangen veroorzaakt geen onverwachte contextwijziging.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Understandable,
    guidelineCode: '3.2',
    guidelineTitleNl: 'Voorspelbaar',
    guidelineDescriptionNl: 'Maak het uiterlijk en de bediening van webpagina\'s voorspelbaar.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/on-focus.html',
  },
  {
    code: '3.2.2',
    titleNl: 'Bij input',
    descriptionNl: 'Invoer wijzigen veroorzaakt geen onverwachte contextwijziging.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Understandable,
    guidelineCode: '3.2',
    guidelineTitleNl: 'Voorspelbaar',
    guidelineDescriptionNl: 'Maak het uiterlijk en de bediening van webpagina\'s voorspelbaar.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/on-input.html',
  },
  {
    code: '3.2.3',
    titleNl: 'Consistente navigatie',
    descriptionNl: 'Navigatiemechanismen die op meerdere pagina\'s voorkomen, staan in dezelfde volgorde.',
    level: WCAGLevel.AA,
    principle: WCAGPrinciple.Understandable,
    guidelineCode: '3.2',
    guidelineTitleNl: 'Voorspelbaar',
    guidelineDescriptionNl: 'Maak het uiterlijk en de bediening van webpagina\'s voorspelbaar.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/consistent-navigation.html',
  },
  {
    code: '3.2.4',
    titleNl: 'Consistente identificatie',
    descriptionNl: 'Alle elementen met dezelfde functie zijn op dezelfde manier herkenbaar.',
    level: WCAGLevel.AA,
    principle: WCAGPrinciple.Understandable,
    guidelineCode: '3.2',
    guidelineTitleNl: 'Voorspelbaar',
    guidelineDescriptionNl: 'Maak het uiterlijk en de bediening van webpagina\'s voorspelbaar.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/consistent-identification.html',
  },
  {
    code: '3.2.6',
    titleNl: 'Consistente hulp',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Understandable,
    guidelineCode: '3.2',
    guidelineTitleNl: 'Voorspelbaar',
    guidelineDescriptionNl: 'Maak het uiterlijk en de bediening van webpagina\'s voorspelbaar.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/consistent-help.html',
  },

  // Guideline 3.3: Assistentie bij invoer
  {
    code: '3.3.1',
    titleNl: 'Foutidentificatie',
    descriptionNl: 'Als fouten gemaakt worden dan moet de fout duidelijk herkenbaar zijn in tekst.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Understandable,
    guidelineCode: '3.3',
    guidelineTitleNl: 'Assistentie bij invoer',
    guidelineDescriptionNl: 'Help gebruikers om fouten te vermijden en ze te verbeteren.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/error-identification.html',
  },
  {
    code: '3.3.2',
    titleNl: 'Labels of instructies',
    descriptionNl: 'Invoervelden hebben duidelijke tekstlabels of instructies.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Understandable,
    guidelineCode: '3.3',
    guidelineTitleNl: 'Assistentie bij invoer',
    guidelineDescriptionNl: 'Help gebruikers om fouten te vermijden en ze te verbeteren.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/labels-or-instructions.html',
  },
  {
    code: '3.3.3',
    titleNl: 'Foutsuggestie',
    descriptionNl: 'Geef oplossingen als gebruikers fouten maken.',
    level: WCAGLevel.AA,
    principle: WCAGPrinciple.Understandable,
    guidelineCode: '3.3',
    guidelineTitleNl: 'Assistentie bij invoer',
    guidelineDescriptionNl: 'Help gebruikers om fouten te vermijden en ze te verbeteren.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/error-suggestion.html',
  },
  {
    code: '3.3.4',
    titleNl: 'Foutpreventie (wettelijk, financieel, gegevens)',
    descriptionNl: 'Acties die juridische verplichtingen, financiële transacties of wijzigingen in gebruikersdata veroorzaken, zijn omkeerbaar.',
    level: WCAGLevel.AA,
    principle: WCAGPrinciple.Understandable,
    guidelineCode: '3.3',
    guidelineTitleNl: 'Assistentie bij invoer',
    guidelineDescriptionNl: 'Help gebruikers om fouten te vermijden en ze te verbeteren.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/error-prevention-legal-financial-data.html',
  },
  {
    code: '3.3.7',
    titleNl: 'Overbodige invoer',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Understandable,
    guidelineCode: '3.3',
    guidelineTitleNl: 'Assistentie bij invoer',
    guidelineDescriptionNl: 'Help gebruikers om fouten te vermijden en ze te verbeteren.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/redundant-entry.html',
  },
  {
    code: '3.3.8',
    titleNl: 'Toegankelijke authenticatie (minimum)',
    level: WCAGLevel.AA,
    principle: WCAGPrinciple.Understandable,
    guidelineCode: '3.3',
    guidelineTitleNl: 'Assistentie bij invoer',
    guidelineDescriptionNl: 'Help gebruikers om fouten te vermijden en ze te verbeteren.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-minimum.html',
  },

  // Principe 4: Robust (Robuust)
  // Guideline 4.1: Compatibel
  {
    code: '4.1.1',
    titleNl: 'Parsen',
    descriptionNl: 'Content heeft geen fouten in de opmaakcode.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Robust,
    guidelineCode: '4.1',
    guidelineTitleNl: 'Compatibel',
    guidelineDescriptionNl: 'Maximaliseer compatibiliteit met huidige en toekomstige user agents, met inbegrip van hulptechnologieën.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/parsing.html',
  },
  {
    code: '4.1.2',
    titleNl: 'Naam, rol en waarde',
    descriptionNl: 'Software begrijpt de naam en rol van elementen. Ook de waarde, status of eigenschappen van elementen kunnen worden bepaald.',
    level: WCAGLevel.A,
    principle: WCAGPrinciple.Robust,
    guidelineCode: '4.1',
    guidelineTitleNl: 'Compatibel',
    guidelineDescriptionNl: 'Maximaliseer compatibiliteit met huidige en toekomstige user agents, met inbegrip van hulptechnologieën.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/name-role-value.html',
  },
  {
    code: '4.1.3',
    titleNl: 'Statusberichten',
    descriptionNl: 'Statusberichten zijn programmatisch bepaalbaar zonder focus te ontvangen.',
    level: WCAGLevel.AA,
    principle: WCAGPrinciple.Robust,
    guidelineCode: '4.1',
    guidelineTitleNl: 'Compatibel',
    guidelineDescriptionNl: 'Maximaliseer compatibiliteit met huidige en toekomstige user agents, met inbegrip van hulptechnologieën.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/status-messages.html',
  },

  // AAA Level Criteria
  {
    code: '1.2.6',
    titleNl: 'Gebarentaal (vooraf opgenomen)',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.2',
    guidelineTitleNl: 'Op tijd gebaseerde media',
    guidelineDescriptionNl: 'Lever alternatieven voor op tijd gebaseerde media.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/sign-language-prerecorded.html',
  },
  {
    code: '1.2.7',
    titleNl: 'Verlengde audiodescriptie (vooraf opgenomen)',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.2',
    guidelineTitleNl: 'Op tijd gebaseerde media',
    guidelineDescriptionNl: 'Lever alternatieven voor op tijd gebaseerde media.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/extended-audio-description-prerecorded.html',
  },
  {
    code: '1.2.8',
    titleNl: 'Media-alternatief (vooraf opgenomen)',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.2',
    guidelineTitleNl: 'Op tijd gebaseerde media',
    guidelineDescriptionNl: 'Lever alternatieven voor op tijd gebaseerde media.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/media-alternative-prerecorded.html',
  },
  {
    code: '1.2.9',
    titleNl: 'Louter-geluid (live)',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.2',
    guidelineTitleNl: 'Op tijd gebaseerde media',
    guidelineDescriptionNl: 'Lever alternatieven voor op tijd gebaseerde media.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/audio-only-live.html',
  },
  {
    code: '1.3.6',
    titleNl: 'Identificeer het doel',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.3',
    guidelineTitleNl: 'Aanpasbaar',
    guidelineDescriptionNl: 'Creëer content die op verschillende manieren gepresenteerd kan worden (bijvoorbeeld eenvoudiger lay-out) zonder verlies van informatie of structuur.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/identify-purpose.html',
  },
  {
    code: '1.4.6',
    titleNl: 'Contrast (versterkt)',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.4',
    guidelineTitleNl: 'Onderscheidbaar',
    guidelineDescriptionNl: 'Maak het voor gebruikers gemakkelijker om content te horen en te zien, waaronder scheiding van voorgrond en achtergrond.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/contrast-enhanced.html',
  },
  {
    code: '1.4.7',
    titleNl: 'Weinig of geen achtergrondgeluid',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.4',
    guidelineTitleNl: 'Onderscheidbaar',
    guidelineDescriptionNl: 'Maak het voor gebruikers gemakkelijker om content te horen en te zien, waaronder scheiding van voorgrond en achtergrond.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/low-or-no-background-audio.html',
  },
  {
    code: '1.4.8',
    titleNl: 'Visuele weergave',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.4',
    guidelineTitleNl: 'Onderscheidbaar',
    guidelineDescriptionNl: 'Maak het voor gebruikers gemakkelijker om content te horen en te zien, waaronder scheiding van voorgrond en achtergrond.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/visual-presentation.html',
  },
  {
    code: '1.4.9',
    titleNl: 'Afbeeldingen van tekst (geen uitzondering)',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Perceivable,
    guidelineCode: '1.4',
    guidelineTitleNl: 'Onderscheidbaar',
    guidelineDescriptionNl: 'Maak het voor gebruikers gemakkelijker om content te horen en te zien, waaronder scheiding van voorgrond en achtergrond.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/images-of-text-no-exception.html',
  },
  {
    code: '2.1.3',
    titleNl: 'Toetsenbord (geen uitzondering)',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.1',
    guidelineTitleNl: 'Toetsenbordtoegankelijk',
    guidelineDescriptionNl: 'Maak alle functionaliteit beschikbaar vanaf een toetsenbord.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/keyboard-no-exception.html',
  },
  {
    code: '2.2.3',
    titleNl: 'Geen timing',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.2',
    guidelineTitleNl: 'Genoeg tijd',
    guidelineDescriptionNl: 'Geef gebruikers voldoende tijd om de content te lezen en te gebruiken.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/no-timing.html',
  },
  {
    code: '2.2.4',
    titleNl: 'Onderbrekingen',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.2',
    guidelineTitleNl: 'Genoeg tijd',
    guidelineDescriptionNl: 'Geef gebruikers voldoende tijd om de content te lezen en te gebruiken.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/interruptions.html',
  },
  {
    code: '2.2.5',
    titleNl: 'Herauthenticatie',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.2',
    guidelineTitleNl: 'Genoeg tijd',
    guidelineDescriptionNl: 'Geef gebruikers voldoende tijd om de content te lezen en te gebruiken.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/re-authenticating.html',
  },
  {
    code: '2.2.6',
    titleNl: 'Time-outs',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.2',
    guidelineTitleNl: 'Genoeg tijd',
    guidelineDescriptionNl: 'Geef gebruikers voldoende tijd om de content te lezen en te gebruiken.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/timeouts.html',
  },
  {
    code: '2.3.2',
    titleNl: 'Drie flitsen',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.3',
    guidelineTitleNl: 'Toevallen en fysieke reacties',
    guidelineDescriptionNl: 'Ontwerp content niet op een manier waarvan bekend is dat die toevallen of fysieke reacties veroorzaakt.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/three-flashes.html',
  },
  {
    code: '2.3.3',
    titleNl: 'Animatie uit interacties',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.3',
    guidelineTitleNl: 'Toevallen en fysieke reacties',
    guidelineDescriptionNl: 'Ontwerp content niet op een manier waarvan bekend is dat die toevallen of fysieke reacties veroorzaakt.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/animation-from-interactions.html',
  },
  {
    code: '2.4.8',
    titleNl: 'Locatie',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.4',
    guidelineTitleNl: 'Navigeerbaar',
    guidelineDescriptionNl: 'Lever manieren om gebruikers te helpen navigeren, content te vinden en te bepalen waar ze zijn.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/location.html',
  },
  {
    code: '2.4.9',
    titleNl: 'Linkdoel (in link)',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.4',
    guidelineTitleNl: 'Navigeerbaar',
    guidelineDescriptionNl: 'Lever manieren om gebruikers te helpen navigeren, content te vinden en te bepalen waar ze zijn.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/link-purpose-link-only.html',
  },
  {
    code: '2.4.10',
    titleNl: 'Paragraafkoppen',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.4',
    guidelineTitleNl: 'Navigeerbaar',
    guidelineDescriptionNl: 'Lever manieren om gebruikers te helpen navigeren, content te vinden en te bepalen waar ze zijn.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/section-headings.html',
  },
  {
    code: '2.4.12',
    titleNl: 'Focus niet bedekt (uitgebreid)',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.4',
    guidelineTitleNl: 'Navigeerbaar',
    guidelineDescriptionNl: 'Lever manieren om gebruikers te helpen navigeren, content te vinden en te bepalen waar ze zijn.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-enhanced.html',
  },
  {
    code: '2.4.13',
    titleNl: 'Focusweergave',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.4',
    guidelineTitleNl: 'Navigeerbaar',
    guidelineDescriptionNl: 'Lever manieren om gebruikers te helpen navigeren, content te vinden en te bepalen waar ze zijn.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance.html',
  },
  {
    code: '2.5.5',
    titleNl: 'Grootte van het aanwijsgebied',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.5',
    guidelineTitleNl: 'Invoermodaliteiten',
    guidelineDescriptionNl: 'Maak het eenvoudiger voor gebruikers om de functionaliteit te bedienen met andere vormen van invoer dan alleen het toetsenbord.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/target-size-enhanced.html',
  },
  {
    code: '2.5.6',
    titleNl: 'Input gelijktijdige invoermechanismen',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Operable,
    guidelineCode: '2.5',
    guidelineTitleNl: 'Invoermodaliteiten',
    guidelineDescriptionNl: 'Maak het eenvoudiger voor gebruikers om de functionaliteit te bedienen met andere vormen van invoer dan alleen het toetsenbord.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/concurrent-input-mechanisms.html',
  },
  {
    code: '3.1.3',
    titleNl: 'Ongebruikelijke woorden',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Understandable,
    guidelineCode: '3.1',
    guidelineTitleNl: 'Leesbaar',
    guidelineDescriptionNl: 'Maak tekstcontent leesbaar en begrijpelijk.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/unusual-words.html',
  },
  {
    code: '3.1.4',
    titleNl: 'Afkortingen',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Understandable,
    guidelineCode: '3.1',
    guidelineTitleNl: 'Leesbaar',
    guidelineDescriptionNl: 'Maak tekstcontent leesbaar en begrijpelijk.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/abbreviations.html',
  },
  {
    code: '3.1.5',
    titleNl: 'Leesniveau',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Understandable,
    guidelineCode: '3.1',
    guidelineTitleNl: 'Leesbaar',
    guidelineDescriptionNl: 'Maak tekstcontent leesbaar en begrijpelijk.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/reading-level.html',
  },
  {
    code: '3.1.6',
    titleNl: 'Uitspraak',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Understandable,
    guidelineCode: '3.1',
    guidelineTitleNl: 'Leesbaar',
    guidelineDescriptionNl: 'Maak tekstcontent leesbaar en begrijpelijk.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/pronunciation.html',
  },
  {
    code: '3.2.5',
    titleNl: 'Verandering op verzoek',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Understandable,
    guidelineCode: '3.2',
    guidelineTitleNl: 'Voorspelbaar',
    guidelineDescriptionNl: 'Maak het uiterlijk en de bediening van webpagina\'s voorspelbaar.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/change-on-request.html',
  },
  {
    code: '3.3.5',
    titleNl: 'Hulp',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Understandable,
    guidelineCode: '3.3',
    guidelineTitleNl: 'Assistentie bij invoer',
    guidelineDescriptionNl: 'Help gebruikers om fouten te vermijden en ze te verbeteren.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/help.html',
  },
  {
    code: '3.3.6',
    titleNl: 'Foutpreventie (alle)',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Understandable,
    guidelineCode: '3.3',
    guidelineTitleNl: 'Assistentie bij invoer',
    guidelineDescriptionNl: 'Help gebruikers om fouten te vermijden en ze te verbeteren.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/error-prevention-all.html',
  },
  {
    code: '3.3.9',
    titleNl: 'Toegankelijke authenticatie (versterkt)',
    level: WCAGLevel.AAA,
    principle: WCAGPrinciple.Understandable,
    guidelineCode: '3.3',
    guidelineTitleNl: 'Assistentie bij invoer',
    guidelineDescriptionNl: 'Help gebruikers om fouten te vermijden en ze te verbeteren.',
    understandingUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-enhanced.html',
  },
];

const researchTypes = [
  {
    name: 'WCAG 2.2 AA onderzoek',
    version: 'WCAG 2.2',
    level: 'AA',
    type: 'website',
    description: 'Volledig onderzoek op 55 succescriteria, conform WCAG 2.2.',
  },
  {
    name: 'WCAG 2.2 AA deelonderzoek content',
    version: 'WCAG 2.2',
    level: 'AA',
    type: 'website',
    description: 'Deelonderzoek content, conform WCAG-EM. Dit onderzoek bevat 33 succescriteria die betrekking hebben op de content van de website.',
  },
  {
    name: 'Trial onderzoek',
    version: 'WCAG 2.2',
    level: 'AA',
    type: 'website',
    description: 'Proef-onderzoek om de functionaliteiten van Cardan Auditor te ervaren',
  },
  {
    name: 'WCAG 2.2 AA – aanvullend deelonderzoek content',
    version: 'WCAG 2.2',
    level: 'AA',
    type: 'website',
    description: 'Aanvullend deelonderzoek gericht op klantspecifieke content binnen de Mijn-omgeving. Dit onderzoekstype wordt gebruikt als aanvulling op een eerder volledig WCAG 2.2 AA-onderzoek van de standaard PIP-omgeving en heeft een afgebakende scope.',
  },
  {
    name: 'WCAG 2.1 AA – volledig onderzoek',
    version: 'WCAG 2.1',
    level: 'AA',
    type: 'website',
    description: 'Volledig onderzoek conform WCAG 2.1 niveau AA.',
  },
  {
    name: 'WCAG 2.0 AA – volledig onderzoek',
    version: 'WCAG 2.0',
    level: 'AA',
    type: 'website',
    description: 'Volledig onderzoek conform WCAG 2.0 niveau AA.',
  },
];

async function main() {
  console.log('Start seeding WCAG 2.2 criteria...');

  for (const criterion of wcagCriteria) {
    await prisma.wCAGCriterion.upsert({
      where: { code: criterion.code },
      update: criterion,
      create: criterion,
    });
  }

  console.log(`Seeded ${wcagCriteria.length} WCAG 2.2 criteria`);

  console.log('Start seeding research types...');

  for (const type of researchTypes) {
    await prisma.researchType.upsert({
      where: { name: type.name },
      update: type,
      create: type,
    });
  }

  console.log(`Seeded ${researchTypes.length} research types`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
