// Hardcoded Quick Findings - Deze bevindingen zijn altijd beschikbaar zonder database

export interface QuickFinding {
  id?: string;
  title: string;
  description: string;
  advice: string;
  criterionCode: string;
  keywords?: string | null;
  crawler?: boolean;
  crawlerTestId?: string | null;
  status?: 'open' | 'published' | 'resolved' | null;
  impact?: 'klein' | 'matig' | 'serieus' | 'kritiek' | 'onbekend' | null;
  responsibility?: 'redacteur' | 'ontwikkelaar' | 'ontwerper' | 'onbekend' | null;
  createdAt?: string;
  updatedAt?: string;
}

export const QUICK_FINDINGS: QuickFinding[] = [
  {
    "id": "63a16431-0d99-4b83-b8f7-7e415b23188b",
    "title": "Afbeelding als link met dubbel tekstalternatief door title en alt",
    "description": "Op pagina URL staat een klikbare afbeelding. De afbeelding staat in een link. Zowel de link als de afbeelding hebben informatie die ervoor zorgen dat ze waarneembaar zijn voor gebruikers van hulpsoftware. Op de link staat een title-attribuut. Op de afbeelding een alt-attribuut. Beiden geven nu dezelfde (of vergelijkbare) informatie. Hierdoor wordt deze informatie dubbel gepresenteerd door hulpsoftware.",
    "advice": "Het advies is om het alt-attribuut te gebruiken voor het tekstalternatief van de afbeelding en alleen het title-attribuut te gebruiken om meer informatie te geven over het linkdoel. Bijvoorbeeld \"Opent in een nieuw venster\".",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "resolved",
    "impact": "klein",
    "responsibility": "ontwikkelaar",
    "createdAt": "2026-02-10T10:19:53.760Z",
    "updatedAt": "2026-02-10T11:04:53.173Z"
  },
  {
    "id": "0b8a2a98-cc9a-4f96-bf0d-3aec05b2cef4",
    "title": "Afbeelding en tekst als aparte links",
    "description": "Op de pagina URL bevindt zich een afbeelding met link en zichtbare tekst met dezelfde link. Hierdoor moet iemand die een toetsenbord gebruikt om door de pagina te navigeren langs beide links.",
    "advice": "Dit kan worden opgelost door de afbeelding en de tekst in één linkelement te plaatsen. Zo wordt de afbeelding decoratief binnen de link en hoeft de gebruiker maar één keer te navigeren.\n\nVoorbeeld:\n\n```html\n<a href=\"\">\n  <img src=\"\" alt=\"\"> Bekijk de details\n</a>\n```\n\nGebruik een lege alt-tekst bij decoratieve afbeeldingen binnen links om dubbele informatie voor schermlezers te voorkomen.",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "resolved",
    "impact": "klein",
    "responsibility": "ontwikkelaar",
    "createdAt": "2026-02-10T10:19:53.762Z",
    "updatedAt": "2026-02-10T11:03:50.937Z"
  },
  {
    "id": "6eaaad27-367d-480b-ae26-454ba6643c34",
    "title": "alt-attribuut ontbreekt",
    "description": "Op pagina URL staat een afbeelding zonder tekstalternatief. Ook het verplichte alt-attribuut ontbreekt. Op een img-element moet altijd een alt-attribuut aanwezig zijn.",
    "advice": "Als de afbeelding informatief is, dan moet het alt-attribuut een correcte omschrijving van de afbeelding geven. Als de afbeelding decoratief is dan moet het alt-attribuut leeg worden gelaten: `alt=\"\"`. Andere oplossingen zijn ook mogelijk.",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "open",
    "impact": "klein",
    "responsibility": "redacteur",
    "createdAt": "2026-02-10T10:19:53.769Z",
    "updatedAt": "2026-02-10T11:02:59.924Z"
  },
  {
    "id": "411c0382-20fa-4b71-a402-283088c7955c",
    "title": "Alt met bestandsnaam (min-tekens, underscore)",
    "description": "Op pagina URL staat een afbeelding waarvan het tekstalternatief bestaat uit een bestandsnaam of technische waarde, zoals `img_398.jpg` of `landschap-met-bomen`. Dit tekstalternatief bevat underscores of mintekens in plaats van gewone spaties. Voor mensen die een schermlezer gebruiken wordt dit letterlijk voorgelezen, waardoor de tekst moeilijk te begrijpen is en de inhoud van de afbeelding niet duidelijk wordt.",
    "advice": "Vervang het technische tekstalternatief door een korte en duidelijke beschrijving van de afbeelding. Gebruik gewone woorden zonder underscores of mintekens, zodat schermlezers het goed kunnen uitspreken.\n\n```html\n<img src=\"landschap-met-bomen.jpg\" alt=\"Landschap met bomen\">\n```\n\nZorg altijd dat het tekstalternatief de inhoud kort samenvat en goed leesbaar is voor iedereen.",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "open",
    "impact": "klein",
    "responsibility": "redacteur",
    "createdAt": "2026-02-10T10:19:53.756Z",
    "updatedAt": "2026-02-10T11:01:49.737Z"
  },
  {
    "id": "71ce379b-f2dd-4ded-8ff1-02069ee0e29f",
    "title": "CAPTCHA geen uitzondering",
    "description": "Op pagina URL wordt een CAPTCHA gebruikt. Deze is niet volledig inhoudelijk getest, omdat de inhoud elke keer anders is. Er is geen gebruik gemaakt van de uitzondering voor CAPTCHA's. De afbeeldingen moeten een tekst(alternatief) krijgen dat het doel van deze afbeeldingen aangeeft en dat is op dit moment niet het geval. Hiernaast moet de CAPTCHA ook op een toegankelijke manier gebruikt kunnen worden. De CAPTCHA moet dus voldoen aan alle overige succescriteria.",
    "advice": "Het advies is om geen gebruik te maken van CAPTCHA's, omdat deze altijd een drempel voor toegankelijkheid zijn. Zie de Engelstalige pagina https://www.w3.org/TR/turingtest/ voor meer informatie en eventuele alternatieven. Het aanbieden van een toegankelijk alternatief voor de hele CAPTCHA is hier eventueel ook een geldige oplossing.",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "open",
    "impact": "onbekend",
    "responsibility": "onbekend",
    "createdAt": "2026-02-10T10:19:53.764Z",
    "updatedAt": "2026-02-10T11:00:29.307Z"
  },
  {
    "id": "f8a71d2a-9091-43f7-a9ca-e9b2f41f60d7",
    "title": "CAPTCHA uitzondering",
    "description": "Op pagina X wordt een CAPTCHA gebruikt. Deze is niet volledig inhoudelijk getest, omdat de inhoud elke keer anders is. Er is gebruik gemaakt van de uitzondering voor CAPTCHA's, die uitzondering zorgt ervoor dat er voldaan wordt aan dit succescriterium. Hiernaast moet de CAPTCHA ook op een toegankelijke manier gebruikt kunnen worden. De CAPTCHA moet dus voldoen aan alle overige succescriteria. ",
    "advice": "Het advies is om geen gebruik te maken van CAPTCHA's, omdat deze altijd een drempel voor toegankelijkheid zijn. Zie de Engelstalige pagina https://www.w3.org/TR/turingtest/ voor meer informatie en eventuele alternatieven. Het aanbieden van een toegankelijk alternatief voor de hele CAPTCHA is ook een optie.",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "resolved",
    "impact": "onbekend",
    "responsibility": "onbekend",
    "createdAt": "2026-02-10T10:19:53.765Z",
    "updatedAt": "2026-02-10T10:59:44.294Z"
  },
  {
    "id": "3bb5cfa2-a90c-48e8-9b86-a9dff5a3f6cd",
    "title": "Complexe afbeelding",
    "description": "Op pagina URL staat een complexe afbeelding. Niet alle gebruikers kunnen de informatie in deze afbeelding goed waarnemen, bijvoorbeeld omdat ze afhankelijk zijn van voorleessoftware of braille.",
    "advice": "De inhoud van deze afbeelding moet in tekst uitgeschreven worden. Deze tekst kan meteen onder de afbeelding staan of als een link of bestand worden toegevoegd. Het tekstalternatief van de afbeelding kan dan verwijzen naar de plek waar deze uitgeschreven tekst staat. Zie ook https://www.w3.org/WAI/tutorials/images/complex/ voor meer tips over hoe een tekstalternatief toe te voegen aan een complexe afbeelding.",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "open",
    "impact": "klein",
    "responsibility": "redacteur",
    "createdAt": "2026-02-10T10:19:53.768Z",
    "updatedAt": "2026-02-10T10:58:24.141Z"
  },
  {
    "id": "e097689a-a55b-46eb-a20f-41b11f19d1ce",
    "title": "CSS Pseudo-element: Decoratief",
    "description": "Op pagina URL wordt met CSS een icoontje geplaatst bij X. Dit icoontje is decoratief, maar hulpsoftware leest deze nu wel voor. Het icoontje is geplaatst met behulp van een CSS pseudo-element (`:before`) of `:after`). De schermlezer leest nu voor: X. Zorg ervoor dat hulpsoftware het icoontje kan negeren.",
    "advice": "Ook met CSS kan worden aangegeven worden of dit icoontje genegeerd moet worden door bijvoorbeeld een schermlezer. Hieronder volgt een voorbeeld:\n```\n.decorative-icon:before {\n  content: \"🐱\" / \"\";\n}\n```\nDe schermlezer zal het icoontje niet meer voorlezen door in de CSS `content` gebruik te maken van een extra _forward-slash_{lang=en} `/` met daarachter een leeg tekstalternatief.\nUitgebreide voorbeelden van hoe tekstalternatieven werken in CSS via pseudo-elementen zijn te vinden in het [code-voorbeeld op CodePen.io](https://codepen.io/cardan-a11y/pen/dyBjWPK).",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "open",
    "impact": "klein",
    "responsibility": "ontwikkelaar",
    "createdAt": "2026-02-10T10:19:53.765Z",
    "updatedAt": "2026-02-10T10:56:33.428Z"
  },
  {
    "id": "3a4376c8-eea7-49b3-b23c-fcc0f0426ad4",
    "title": "CSS Pseudo-element: Tekstalternatief ontbreekt",
    "description": "Op pagina URL wordt met CSS een icoontje geplaatst bij X. Dit icoontje is informatief, maar er is geen tekstalternatief beschikbaar. Hierdoor is de informatie van dit icoontje niet waarneembaar voor iedereen die afhankelijk is van een schermlezer of braille. Een tekstalternatief is altijd verplicht voor informatieve icoontjes, ook als icoontjes worden geplaatst met pseudo-elementen via CSS.",
    "advice": "Via CSS kan het tekstalternatief worden geplaatst. Pas hiervoor de CSS aan van het pseudo-element (`:before` of `:after`). \nEen voorbeeld:\n```\n.informative-icon:before {\n  content: \"\\25BA / \"Tekst alternatief\";\n}\n```\nUitgebreide voorbeelden van hoe tekstalternatieven werken in CSS via pseudo-elementen zijn te vinden in het [code-voorbeeld op CodePen.io](https://codepen.io/cardan-a11y/pen/dyBjWPK).",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "open",
    "impact": "matig",
    "responsibility": "ontwikkelaar",
    "createdAt": "2026-02-10T10:19:53.766Z",
    "updatedAt": "2026-02-10T10:55:21.676Z"
  },
  {
    "id": "f936aa29-40bb-41e0-a7b5-753c5520d59a",
    "title": "Decoratieve afbeelding zonder lege alt-tekst",
    "description": "Op pagina URL is één of meerdere decoratieve afbeeldingen voorzien van een tekstalternatief via het alt-attribuut. Hierdoor worden deze afbeeldingen ook gepresenteerd aan bezoekers die gebruik maken van een schermlezer, terwijl de afbeeldingen in dit geval geen inhoudelijke informatie toevoegen aan de pagina. Dit kan leiden tot onnodige onderbrekingen tijdens het navigeren en bemoeilijkt het snel scannen van de relevante inhoud.",
    "advice": "Zorg dat decoratieve afbeeldingen worden genegeerd door hulpsoftware. Dit kan door een leeg tekstalternatief te gebruiken (alt=\"\") of de afbeelding op te maken als achtergrondafbeelding via CSS. Zo blijft de pagina overzichtelijk voor gebruikers van een schermlezer, terwijl het visuele ontwerp behouden blijft.",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "open",
    "impact": "klein",
    "responsibility": "redacteur",
    "createdAt": "2026-02-10T10:19:53.757Z",
    "updatedAt": "2026-02-10T10:54:17.403Z"
  },
  {
    "id": "07563f80-5daa-47b2-8552-d40f25252125",
    "title": "Decoratieve SVG",
    "description": "Op pagina URL staan decoratieve svg's. Deze zijn niet verborgen voor hulpsoftware. Dit keuren we niet af, maar het is wel beter om de elementen te verbergen. Zo voorkom je dat er overbodige of onduidelijke informatie wordt gepresenteerd aan gebruikers van hulpsoftware.",
    "advice": "Verberg decoratieve SVG’s voor hulpsoftware zodat ze niet onnodig worden voorgelezen. Dit kan door `aria-hidden=\"true\"` toe te voegen aan het `<svg>`-element.\n\n```html\n<svg aria-hidden=\"true\" ...>\n  <!-- decoratieve inhoud -->\n</svg>\n```\n\nZorg er ook voor dat de SVG geen onnodige `title`- of `desc`-elementen bevat. Zo blijft de ervaring helder voor gebruikers van schermlezers.",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "resolved",
    "impact": "klein",
    "responsibility": "ontwikkelaar",
    "createdAt": "2026-02-10T10:19:53.758Z",
    "updatedAt": "2026-02-10T10:53:40.962Z"
  },
  {
    "id": "e47cb9a1-da15-4fdd-bc31-4bb99dfef45c",
    "title": "Functioneel icoon zonder toegankelijke naam",
    "description": "Een icoon dat een functie heeft (zoals VOORBEELD) bevat geen toegankelijke naam of label. Zonder toegankelijke naam blijft de actie onduidelijk voor screenreadergebruikers.",
    "advice": "Voeg een toegankelijke naam toe met aria-label, aria-labelledby of een bijschrift dat de functie beschrijft (bijv. \"VOORBEELD\").",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "open",
    "impact": "klein",
    "responsibility": "ontwikkelaar",
    "createdAt": "2026-02-10T10:19:53.761Z",
    "updatedAt": "2026-02-10T10:52:32.305Z"
  },
  {
    "id": "107f8c79-2fdd-4bf9-9a7f-0ae4665c43cc",
    "title": "Icoon extern venster zonder tekstalternatief",
    "description": "Op de pagina URL bevindt zich een icoon wat communiceert dat een link wordt geopend in een nieuw venster. Dit icoon mist een tekstalternatief. Hierdoor wordt niet gepresenteerd door hulpsoftware dat de link in een nieuw venster zal openen.",
    "advice": "Over het algemeen wordt afgeraden links in een nieuw venster te openen. Mocht dit toch nodig/wenselijk zijn in de context, voeg dan een tekstalternatief toe aan het icoon, bijvoorbeeld \"Opent in nieuw venster\".",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "open",
    "impact": "matig",
    "responsibility": "redacteur",
    "createdAt": "2026-02-10T10:19:53.762Z",
    "updatedAt": "2026-02-10T10:52:00.600Z"
  },
  {
    "id": "ddd2abee-d038-448d-95cd-06226dcec2e0",
    "title": "Kaart",
    "description": "Op pagina X staat een kaart. De informatie in deze kaart is niet toegankelijk voor een blinde gebruiker.",
    "advice": "De kaart kan toegankelijk gemaakt worden door een tekstalternatief te bieden die voorgelezen kan worden door hulpsoftware. Een van de mogelijke oplossingen is het aanbieden van een toegankelijke datatabel waarin dezelfde informatie wordt gepresenteerd.\n\nVoor elk item in een legenda moet informatie worden gegeven. Een item dat niet voorkomt, moet ook beschreven worden. Het feit dat een item niet op de kaart staat, is ook informatie die moet worden overgedragen, want anders zou deze niet in de legenda staan.\n\nEen kaart-applicatie heeft geen tekstalternatief nodig als de kaart zelf toegankelijk is. Alle afbeeldingen in de kaart moeten een goed tekstalternatief hebben, of zij nu decoratief zijn of niet. Voor een kaart als geheel mag ook een alternatief geboden worden. Als de kaart als enige doel heeft om een adres weer te geven, dan is het adres in de tekst ook goed als toegankelijk alternatief.",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "open",
    "impact": "matig",
    "responsibility": "redacteur",
    "createdAt": "2026-02-10T10:19:53.764Z",
    "updatedAt": "2026-02-10T10:50:59.391Z"
  },
  {
    "id": "d9d24227-4e8d-4c2f-b00a-479811822ace",
    "title": "Kaart voor navigatie",
    "description": "Op pagina URL staat een kaart die bedoeld is voor navigatie. De essentiële informatie uit deze kaart moet daarom op een toegankelijke manier worden aangeboden. De kaart zelf is verder niet onderzocht.",
    "advice": "Zorg dat de adressen ook op de website worden aangeboden als standaard tekst.",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "open",
    "impact": "klein",
    "responsibility": "redacteur",
    "createdAt": "2026-02-10T10:19:53.767Z",
    "updatedAt": "2026-02-10T10:49:21.602Z"
  },
  {
    "id": "cf44faa4-3b82-4ec3-9b63-09293591ceb0",
    "title": "Op tijd gebaseerde media mist tekstalternatief",
    "description": "Op pagina URL bevindt zicht een video waarvoor een onvoldoende tekstalternatief beschikbaar is. Voor de ziende persoon is het snel duidelijk dat er een video staat en waar deze video over gaat. Deze informatie moet ook beschikbaar zijn voor bezoekers die afhankelijk zijn van hulpsoftware zoals een schermlezer of braille. ",
    "advice": "Zorg dat het tekstalternatief van de video duidelijk maakt dat het om een video gaat en wat de inhoud ervan is. Beschrijf kort het onderwerp of doel van de video, zodat ook gebruikers van schermlezers of braille een goed beeld krijgen van de context.\n\nPlaats bij voorkeur een korte inleidende tekst direct boven de video, bijvoorbeeld:\n\nVideo: uitleg over het maken van toegankelijke documenten.\n\nVul dit eventueel aan met een aria-label of title-attribuut bij de videospeler of het iframe waarin de video staat.\n\nVoorbeeld:\n\n```html\n<p>In onderstaande video leer je meer over het maken van toegankelijke documenten.</p>\n<iframe src=\"video.mp4\" title=\"Video: Toegankelijke documenten maken\"></iframe>\n```\n\nOf met een eigen videospeler:\n\n```html\n<video controls aria-label=\"Video: Toegankelijke documenten maken\">\n  <source src=\"video.mp4\" type=\"video/mp4\">\n</video>\n```\n\nCombineer waar mogelijk beide vormen: een tekstuele omschrijving boven de video en een toegankelijke naam van de videospeler. Zo wordt de informatie begrijpelijk voor alle gebruikers.",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "open",
    "impact": "matig",
    "responsibility": "redacteur",
    "createdAt": "2026-02-10T10:19:53.759Z",
    "updatedAt": "2026-02-10T10:48:44.223Z"
  },
  {
    "id": "455a8cca-9b7a-47ac-9542-cfc361953cd8",
    "title": "PDF - Afbeeldingen niet-getagde PDF",
    "description": "Het volgende PDF-document is niet getagd. Hierdoor zijn informatieve afbeeldingen niet gemarkeerd als `<Figure>` en hebben zij geen tekstalternatief. Mensen die blind zijn en een schermlezer gebruiken krijgen deze informatie daardoor niet aangeboden. Omdat het document niet is getagd, is niet vast te stellen of afbeeldingen correct zijn verwerkt. Hierdoor wordt dit nu niet afgekeurd. Zodra het document wel wordt getagd, kan blijken dat informatieve afbeeldingen ontbreken of onjuist zijn getagd.",
    "advice": "Zorg dat de PDF wordt voorzien van een volledige tags-structuur en maak daarbij onderscheid tussen informatieve en decoratieve afbeeldingen.\n\n- Tag informatieve afbeeldingen als `<Figure>` en geef deze van een kort en beschrijvend tekstalternatief dat de functie of inhoud van de afbeelding samenvat.\n- Markeer decoratieve afbeeldingen als artefact zodat deze worden genegeerd door schermlezers.",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "resolved",
    "impact": "serieus",
    "responsibility": "redacteur",
    "createdAt": "2026-02-10T10:19:53.755Z",
    "updatedAt": "2026-02-10T10:47:27.078Z"
  },
  {
    "id": "b59abf88-a99f-4a9a-8bd8-d880a28935c8",
    "title": "PDF - Complexe afbeelding",
    "description": "In het volgende PDF-document staat een complexe afbeeldig op pagina X. Een blinde gebruiker is nu uitgesloten van de informatie die in deze complexe afbeelding staat.",
    "advice": "De inhoud van deze afbeelding moet in tekst uitgeschreven worden. Deze tekst kan meteen onder de afbeelding staat of als een link of bestand worden toegevoegd. Het tekstalternatief van de afbeelding kan dan verwijzen naar de plek waar deze uitgeschreven tekst staat.",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "open",
    "impact": "matig",
    "responsibility": "redacteur",
    "createdAt": "2026-02-10T10:19:53.767Z",
    "updatedAt": "2026-02-10T10:46:45.667Z"
  },
  {
    "id": "30e8a701-d7de-4936-96e9-4200039d872a",
    "title": "PDF - Decoratieve afbeelding is geen artefact",
    "description": "In het PDF-document DOCUMENT bevinden zich decoratieve afbeeldingen die getagd zijn als `<Figure>`. Hierdoor wordt de afbeelding gepresenteerd door hulpsoftware terwijl dit niet de bedoeling is.",
    "advice": "Afbeeldingen in PDF's kunnen als `artefact` worden gemarkeerd, hierdoor worden ze niet meer gepresenteerd door hulpsoftware. Dit kan in nieuwere versies van Microsoft Word worden gedaan door de afbeelding te markeren als decoratief. In Adobe InDesign kan een afbeelding ook als decoratief worden gemarkeerd. Als dit niet is gebeurd, kan de auteur via Adobe Acrobat Pro de afbeelding als achtergrond of `<Artefact>` markeren. Dan verdwijnt de afbeelding uit de tags.",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "open",
    "impact": "matig",
    "responsibility": "redacteur",
    "createdAt": "2026-02-10T10:19:53.758Z",
    "updatedAt": "2026-02-10T10:45:42.236Z"
  },
  {
    "id": "96e38319-53ba-4647-94bf-1ccc45e4190d",
    "title": "PDF - Niet-getagd logo",
    "description": "In het volgende PDF-document staat bovenin het logo van ORGANISATIE. Dit logo is niet als afbeelding getagd en wordt daarom genegeerd.",
    "advice": "Op pagina 1 moet dit logo wel een afbeelding worden en een goed tekstalternatief krijgen. Op de vervolgpagina's is dat niet nodig en zelfs niet gewenst, omdat dit daar de leesvolgorde kan onderbreken.",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "open",
    "impact": "klein",
    "responsibility": "redacteur",
    "createdAt": "2026-02-10T10:19:53.768Z",
    "updatedAt": "2026-02-10T10:44:41.411Z"
  },
  {
    "id": "c134b1ff-7a22-4d3d-a698-ea3d535144de",
    "title": "Rijksoverheid lint",
    "description": "Op alle pagina's staat het beeldmerk (lint) van de Rijksoverheid, te herkennen aan een donkerblauw balkje met daarin een \"wapen\". Het gebruik van dit lint toont aan dat deze website en de organisatie onderdeel is van de Rijksoverheid. Het lint is daarom informatief. Er is nu geen tekstalternatief voor deze informatie beschikbaar.",
    "advice": "Voeg het woord \"Rijksoverheid\" toe aan het tekstalternatief.",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "open",
    "impact": "klein",
    "responsibility": "redacteur",
    "createdAt": "2026-02-10T10:19:53.761Z",
    "updatedAt": "2026-02-10T10:43:55.887Z"
  },
  {
    "id": "15596e94-8450-4d65-888d-31fb7a91ba93",
    "title": "Te lang alt-attribuut",
    "description": "Op pagina URL staat een afbeelding met een erg lang tekstalternatief. Het tekstalternatief bestaat uit één lange waarde in het alt-attribuut. Dit is lastig voor mensen die een schermlezer gebruiken, omdat de informatie zonder structuur wordt voorgelezen. Hierdoor is het moeilijk om de inhoud te begrijpen, vooral als de afbeelding veel details bevat.",
    "advice": "Gebruik voor (complexe) afbeeldingen geen lang tekstalternatief in het `alt`-attribuut. Beperk het `alt`-attribuut tot een korte beschrijving van de afbeelding. Het advies is een tekstalternatief van maximaal 75 tekens. Plaats de uitgebreide uitleg ergens anders op de pagina, bijvoorbeeld in een aparte alinea of via een toegankelijke link naar een langere beschrijving.\n\nVoorbeeld:\n\n```html\n<img src=\"diagram.png\" alt=\"Overzicht van de organisatiestructuur. Zie beschrijving onder afbeelding.\">\n<p id=\"diagram-beschrijving\">\n  Beschrijving van het diagram: de organisatie bestaat uit drie afdelingen: Communicatie, Ontwikkeling en Onderzoek. \n  Onder elke afdeling vallen twee teams, die samen rapporteren aan het managementteam.\n</p>\n```\n\nOf, als de uitgebreide beschrijving elders staat:\n\n```html\n<img src=\"diagram.png\" alt=\"Overzicht van de organisatiestructuur. Zie pagina met toelichting.\">\n```\n\nZorg ervoor dat de beknopte tekst in het `alt`-attribuut het doel van de afbeelding samenvat. Zo blijft de afbeelding begrijpelijk voor gebruikers van schermlezers en voldoet de pagina aan WCAG 1.1.1.\n\nDit probleem komt ook voor op pagina URL.",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "resolved",
    "impact": "klein",
    "responsibility": "redacteur",
    "createdAt": "2026-02-10T10:19:53.756Z",
    "updatedAt": "2026-02-10T10:42:44.598Z"
  },
  {
    "id": "f67ef80b-9e55-4dca-b6e2-21a4969ea031",
    "title": "Tekstalternatief height/width 0",
    "description": "Op de pagina URL bevinden zich afbeeldingen waarvan het tekstalternatief verborgen wordt door het gebruik van `height:0;`, `width:0;` of `font-size:0;`. De presentatie van hulpsoftware verschilt bij het gebruik hiervan, waardoor het tekstalternatief bij sommigen wel en bij anderen niet wordt gepresenteerd. ",
    "advice": "Verwijder `height:0;`, `width:0;` of `font-size:0;` van de tekstalternatieven om deze gelijkwaardig beschikbaar te maken voor hulpsoftware. Tekst die visueel verborgen is, maar voor hulpsoftware wel beschikbaar moet zijn, moet op een andere manier verborgen worden. Dit kan bijvoorbeeld met een `.sr-only` class in CSS of met de clip-methode.",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "open",
    "impact": "klein",
    "responsibility": "ontwikkelaar",
    "createdAt": "2026-02-10T10:19:53.760Z",
    "updatedAt": "2026-02-10T10:40:40.804Z"
  },
  {
    "id": "60f79d7a-49a6-45ed-92ee-96ff9697f0b4",
    "title": "Tekstalternatief met \"Afbeelding van...\"",
    "description": "Op pagina (URL) staan afbeeldingen met een tekstalternatief dat begint met woorden als \"Afbeelding van\" of \"Foto van\". Voor mensen die een schermlezer of brailleleesregel gebruiken is dit niet nodig. Hulpsoftware geeft namelijk al aan dat het om een afbeelding gaat. Door deze extra woorden wordt de informatie langer en minder prettig om te beluisteren of te lezen.",
    "advice": "Laat in het tekstalternatief woorden als \"afbeelding\", \"foto\" of \"plaatje\" weg en beschrijf direct de inhoud of functie van de afbeelding.\n\nVoorbeeld:\n\n```html\n<img src=\"team.jpg\" alt=\"Projectteam in overleg aan een tafel\">\n```\n\nIn specifieke situaties is het wel zinvol om het type afbeelding te noemen. Doe dit alleen als het verschil belangrijk is voor het begrip.\n\nVoorbeelden:\n\n• Een schets van een straatbeeld in plaats van een foto van die straat.\n• Een karikatuur van een persoon in plaats van een foto van die persoon.\n\nVoorbeeld:\n\n```html\n<img src=\"straat-schets.png\" alt=\"Schets van een druk stadsplein met mensen\">\n```",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "resolved",
    "impact": "klein",
    "responsibility": "redacteur",
    "createdAt": "2026-02-10T10:19:53.753Z",
    "updatedAt": "2026-02-10T10:33:23.117Z"
  },
  {
    "id": "76cb5a4c-8c18-4649-a2d6-3a8bd7714ff7",
    "title": "Tekstalternatief verborgen",
    "description": "Op pagina URL bevinden zich afbeeldingen waarbij het tekstalternatief verborgen is met `display:none`, `visibility:hidden` of `aria-hidden=\"true\"`. Hierdoor is het tekstalternatief niet beschikbaar voor hulpsoftware.",
    "advice": "Verwijder `display:none`, `visibility:hidden` of `aria-hidden=\"true\"` van het tekstalternatief zodat deze weer beschikbaar wordt voor hulpsoftware. Tekst die visueel verborgen is, maar voor hulpsoftware wel beschikbaar moet zijn, moet op een andere manier verborgen worden. Dit kan bijvoorbeeld met een .sr-only class in CSS of met de clip-methode.",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "open",
    "impact": "matig",
    "responsibility": "ontwikkelaar",
    "createdAt": "2026-02-10T10:19:53.763Z",
    "updatedAt": "2026-02-10T10:30:06.988Z"
  },
  {
    "id": "9913caf9-55f7-4740-ba4c-94facaa6adce",
    "title": "Tekstalternatieven complexe afbeelding",
    "description": "Op pagina URL bevindt zicht een complexe afbeelding. Dit soort complexe afbeeldingen moeten voorzien worden van zowel een kort- als lang tekstalternatief. Deze is/zijn in dit geval onvoldoende aanwezig.",
    "advice": "Zorg voor een kort tekstalternatief die een beknopte beschrijving geeft van de afbeelding. Dit kan bijvoorbeeld met het alt-atribuut. Zorg ook voor een lang tekstalternatief. Deze geeft een uitgebreide beschrijving van dezelfde informatie die in de afbeelding wordt overgebracht. Dit kan bijvoorbeeld door middel van een tabel of een uitgeschreven tekst. Deze tekst kan dan bijvoorbeeld onder de afbeelding staan of in een uitklapbaar onderdeel bij de afbeelding. De beschrijving kan ook op een andere pagina staan waar dan met een link naar toe wordt verwezen.",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "open",
    "impact": "matig",
    "responsibility": "redacteur",
    "createdAt": "2026-02-10T10:19:53.763Z",
    "updatedAt": "2026-02-10T10:30:54.328Z"
  },
  {
    "id": "befb62ba-a38b-4ad7-97de-40ccd089b87c",
    "title": "Video of animatie zonder tekstalternatief",
    "description": "Op pagina URL staat een video. Bij deze video ontbreekt een tekstalternatief. Een ziende gebruiker kan zien dat er een video staat en waar de video over gaat. Als je afhankelijk bent van een schermlezer moet het tekstalternatief vertellen wat er staat (een video) en waar deze over gaat, bijvoorbeeld \"Video: X\".",
    "advice": "Voor een video of animatie geldt dat er direct vóór (bij voorkeur) of direct na de video een korte omschrijving staat van wat in de video of animatie te zien is. Dit kan bijvoorbeeld met een titel (bijvoorbeeld in een kop) die direct boven de video staat, of in een zin of alinea direct boven de video.\n\nDe uitleg mag ook verder weg staan van de video, maar alleen als er een directe verwijzing staat naar de video.\n\nLet op: In YouTube-video's staat ook vaak een titel in de video zelf. Dit volstaat niet als titel of omschrijving van de video.",
    "criterionCode": "1.1.1",
    "keywords": null,
    "crawler": false,
    "crawlerTestId": null,
    "status": "open",
    "impact": "onbekend",
    "responsibility": "redacteur",
    "createdAt": "2026-02-10T10:19:53.766Z",
    "updatedAt": "2026-02-10T10:27:29.529Z"
  }
];
