/**
 * WCAG 2.2 → crawler-test mapping.
 *
 * Wordt gebruikt door de Richtlijnen-tab om per SC te tonen welke
 * automatische tests we hebben en wat ze opleveren voor dit project.
 *
 * Bron-of-truth voor de mapping. Bij toevoeging van een test in tests.ts of
 * browser-tests.ts: voeg hier ook een regel toe.
 */

export type TestSource = 'html' | 'browser';

/**
 * Wie is de eerste verantwoordelijke voor het oplossen van dit type fout?
 * - `content`: redacteur — fout zit in losse content (alt-tekst, lege koppen, link-teksten)
 * - `template`: ontwikkelaar — fout zit in het CMS-template (landmarks, ARIA, structuur)
 * - `ontwerp`: ontwerper — fout zit in de visuele keuze (kleurcontrast, font-size)
 * - `mixed`: hangt af van het concrete geval (bv. contrast kan content of ontwerp zijn)
 */
export type TestResponsibility = 'content' | 'template' | 'ontwerp' | 'mixed';

export interface TestCoverage {
  testName: string;
  titleNl: string;
  source: TestSource;
  scs: string[]; // WCAG SC-codes
  responsibility: TestResponsibility;
  note?: string;
  /** Korte uitleg waarom dit een probleem is — leesbaar Nederlands voor de detail-pagina. */
  descriptionNl?: string;
  /** Uitgebreide uitleg (impact, oorzaken, voorbeelden) — Siteimprove "Meer informatie"-stijl. */
  moreInfoNl?: string;
}

export const TEST_COVERAGE: TestCoverage[] = [
  // ---- HTML-tests (tests.ts) ----
  { testName: 'LangAttributeMissingTest', titleNl: 'Lang-attribuut ontbreekt op pagina', source: 'html', scs: ['3.1.1'], responsibility: 'template', descriptionNl: 'Het html-element van de pagina mist het lang-attribuut.', moreInfoNl: 'Hulpsoftware kijkt naar het lang-attribuut van het html-element om te bepalen welke taal en uitspraak gebruikt moet worden bij het voorlezen. Zonder dit attribuut leest een schermlezer Nederlandse tekst mogelijk met een Engelse uitspraak voor — onbegrijpelijk voor de gebruiker.\n\nZet altijd lang="nl" (of een andere ISO-taalcode) op het html-element. Voor anderstalige passages binnen de pagina kan een element ook een eigen lang-attribuut krijgen.' },
  { testName: 'TitleMissingTest', titleNl: 'Pagina mist een titel', source: 'html', scs: ['2.4.2'], responsibility: 'template', descriptionNl: 'De pagina heeft geen title-element in de head.', moreInfoNl: 'De paginatitel verschijnt in de browser-tab, in zoekresultaten en wordt als eerste door schermlezers voorgelezen wanneer een pagina opent. Zonder titel weet de gebruiker niet welke pagina hij heeft geopend.\n\nGeef elke pagina een unieke, beschrijvende titel die het hoofdonderwerp aangeeft. Een veelgebruikt patroon is "Onderwerp | Organisatienaam" (bijvoorbeeld "Paspoort aanvragen | Gemeente Valkenswaard").' },
  { testName: 'TitleEmptyTest', titleNl: 'Pagina heeft een lege titel', source: 'html', scs: ['2.4.2'], responsibility: 'template', descriptionNl: 'Het title-element bestaat maar bevat geen tekst.', moreInfoNl: 'Een leeg title-element is net zo onbruikbaar als een ontbrekend title-element. De browser-tab toont niets, en hulpsoftware kondigt de pagina niet aan met een herkenbare naam.\n\nVul de titel met een unieke, beschrijvende tekst die het onderwerp van de pagina aangeeft.' },
  { testName: 'ImgMissingAltTest', titleNl: 'Afbeelding mist een tekstalternatief', source: 'html', scs: ['1.1.1'], responsibility: 'content', descriptionNl: 'Een afbeelding (img-element) heeft geen alt-attribuut.', moreInfoNl: 'Afbeeldingen zonder tekstalternatief zijn onzichtbaar voor mensen die de website laten voorlezen door een schermlezer. Voor blinde en slechtziende gebruikers gaat informatie verloren als de boodschap alleen in beeld staat.\n\nGeef informatieve afbeeldingen (zoals een foto bij een nieuwsbericht, een infographic of een grafiek) een alt-tekst die overbrengt wat de afbeelding wil zeggen — niet wat erop te zien is. Bij een logo volstaat meestal de organisatienaam.\n\nVoor puur decoratieve afbeeldingen die niets toevoegen aan de inhoud (zoals een achtergrondvorm of een sierlijn) hoor je een leeg alt-attribuut (alt="") te plaatsen. De schermlezer slaat de afbeelding dan over.' },
  { testName: 'DecorativeImageExposedTest', titleNl: 'Decoratieve afbeelding wordt blootgesteld aan hulpsoftware', source: 'html', scs: ['1.1.1'], responsibility: 'mixed', descriptionNl: 'Een afbeelding is gemarkeerd als decoratief (alt="", role="presentation" of aria-hidden="true") maar wordt door andere attributen tóch zichtbaar voor hulpsoftware.', moreInfoNl: 'Een decoratieve afbeelding hoort onzichtbaar te zijn voor schermlezers. Maar als er tegelijkertijd een aria-label, title-attribuut of tabindex op staat — of als de afbeelding in een link of knop zit zonder andere toegankelijke naam — wordt ze tóch voorgelezen of focusbaar.\n\nDat is verwarrend voor de gebruiker: een afbeelding die niets toevoegt, krijgt toch aandacht. Of een schijnbaar lege link wordt focusbaar en de gebruiker weet niet waarheen die leidt.\n\nKies één van twee opties: óf de afbeelding is echt decoratief — verwijder dan álle naam-gevende attributen (geen aria-label, geen title, geen tabindex, en zorg voor andere tekst in de link of knop). Óf de afbeelding is functioneel — geef hem dan een betekenisvolle alt-tekst.' },
  { testName: 'ImgAltTooLongTest', titleNl: 'Tekstalternatief is erg lang', source: 'html', scs: ['1.1.1'], responsibility: 'content', note: 'kwaliteit alt-tekst', descriptionNl: 'De alt-tekst van een afbeelding is langer dan 125 tekens.', moreInfoNl: 'Een goede alt-tekst is kort en kernachtig. Schermlezers lezen alt-teksten in één adem voor — bij lange teksten raakt de gebruiker de draad kwijt en kan hij niet meer goed naar andere content luisteren.\n\nAls de afbeelding zoveel informatie bevat dat een korte alt niet voldoet, zet de uitleg dan in de omringende tekst of in een aparte beschrijving op de pagina. De alt-tekst kan dan kort verwijzen naar die uitleg ("Diagram, beschrijving onder de afbeelding").' },
  { testName: 'ImgAltTooShortTest', titleNl: 'Tekstalternatief is erg kort', source: 'html', scs: ['1.1.1'], responsibility: 'content', note: 'kwaliteit alt-tekst', descriptionNl: 'De alt-tekst van een afbeelding is 1 of 2 tekens lang.', moreInfoNl: 'Een alt-tekst van één of twee tekens (zoals "a", "x" of een cijfer) is bijna altijd betekenisloos. Meestal is alt vergeten en heeft een editor per ongeluk iets typt, of stond er een placeholder die niet vervangen is.\n\nGeef de afbeelding een echte beschrijvende alt-tekst die de informatie overbrengt. Is de afbeelding decoratief en bedoeld om door schermlezers te worden overgeslagen, gebruik dan een leeg alt-attribuut: alt="".' },
  { testName: 'ImageLinkMissingAccessibleNameTest', titleNl: 'Afbeelding-link mist een toegankelijke naam', source: 'html', scs: ['1.1.1', '2.4.4', '4.1.2'], responsibility: 'content', descriptionNl: 'Een link bestaat uit alleen een afbeelding, en die afbeelding heeft geen alt-tekst terwijl de link ook geen aria-label of zichtbare tekst heeft.', moreInfoNl: 'Hulpsoftware kondigt de link aan zonder te zeggen waarheen die gaat. Vaak leest een schermlezer dan de bestandsnaam voor (bijvoorbeeld "logo-2024-final-v3.jpg") of zegt alleen "link" zonder context. Voor blinde en slechtziende gebruikers is de link daardoor onbruikbaar.\n\nDit raakt drie WCAG-criteria tegelijk: 1.1.1 (afbeelding zonder tekstalternatief), 2.4.4 (linkdoel niet te bepalen) en 4.1.2 (element zonder toegankelijke naam).\n\nOplossing: geef de afbeelding een passende alt-tekst die beschrijft waar de link naartoe gaat (niet wat er op de afbeelding staat). Of geef de link zelf een aria-label, of voeg zichtbare tekst toe naast de afbeelding.' },
  { testName: 'ImageButtonMissingAltTest', titleNl: 'Afbeeldingsknop mist een tekstalternatief', source: 'html', scs: ['1.1.1', '4.1.2'], responsibility: 'content', descriptionNl: 'Een input type="image" mist het alt-attribuut.', moreInfoNl: 'Een input type="image" is een knop die een afbeelding als label gebruikt — een native HTML image-button die meestal in oudere formulieren staat. Zonder alt-attribuut kondigt hulpsoftware deze aan als alleen "knop", zonder doel.\n\nGeef elke image-button een alt-tekst die het doel beschrijft (bijvoorbeeld alt="Zoeken" voor een zoekknop). Een leeg alt is hier niet gepast omdat de knop een actie uitvoert.' },
  { testName: 'AltIsFilenameTest', titleNl: 'Tekstalternatief is een bestandsnaam', source: 'html', scs: ['1.1.1'], responsibility: 'content', note: 'kwaliteit alt-tekst', descriptionNl: 'De alt-tekst van een afbeelding lijkt op de bestandsnaam (zoals "IMG_5847.png" of "logo-final-v3").', moreInfoNl: 'Veel content-management-systemen vullen automatisch de bestandsnaam in als alt-tekst zodra een redacteur een afbeelding uploadt. Dat is bijna altijd betekenisloos voor de gebruiker: "DSC_1234.jpg" zegt niets over wat er op de foto staat.\n\nVoor schermlezer-gebruikers wordt elke afbeelding dan een onsamenhangende reeks letters en cijfers. Ook search engines en hulpsoftware kunnen er weinig mee.\n\nVervang de bestandsnaam door een echte beschrijving die de informatie van de afbeelding overbrengt. Voor decoratieve afbeeldingen kan een leeg alt (alt="") — dan slaat de schermlezer de afbeelding over.' },
  { testName: 'SvgMissingAccessibleNameTest', titleNl: 'SVG-afbeelding mist een toegankelijke naam', source: 'html', scs: ['1.1.1', '4.1.2'], responsibility: 'template', descriptionNl: 'Een inline SVG-element heeft geen toegankelijke naam (geen aria-label, aria-labelledby of title-element).', moreInfoNl: 'SVG-afbeeldingen worden veel gebruikt voor iconen, logos en illustraties. Anders dan een img-tag hebben ze geen alt-attribuut — de toegankelijke naam komt uit een title-element (eerste kind van de svg), of uit aria-label / aria-labelledby op de svg zelf.\n\nZonder toegankelijke naam kondigt hulpsoftware de SVG aan als alleen "afbeelding" of soms helemaal niets. Voor blinde en slechtziende gebruikers gaat de informatie verloren.\n\nVoeg een title-element toe als eerste kind van de svg (<title>Logo gemeente</title>), of zet aria-label op de svg-tag. Voor puur decoratieve SVGs (zoals een sierlijn): zet role="presentation" of aria-hidden="true".' },
  { testName: 'ObjectMissingAltTest', titleNl: 'Object mist een tekstalternatief', source: 'html', scs: ['1.1.1', '4.1.2'], responsibility: 'template', descriptionNl: 'Een object-element heeft geen fallback-tekst, aria-label of title.', moreInfoNl: 'Het object-element wordt gebruikt om externe inhoud in te voegen, zoals een PDF-viewer, een Flash-applet of een 3D-model. Zonder fallback-tekst weet hulpsoftware niet wat er ingebed is.\n\nVoeg een toegankelijke naam toe via aria-label, of zet beschrijvende tekst tussen de open- en sluit-tag (<object>...<p>Beschrijving van de inhoud</p></object>). Die fallback-tekst wordt door browsers getoond als het object niet kan laden, en door hulpsoftware voorgelezen als alternatief.' },
  { testName: 'IframeMissingAccessibleNameTest', titleNl: 'Iframe mist een toegankelijke naam', source: 'html', scs: ['4.1.2', '2.4.6'], responsibility: 'content', descriptionNl: 'Een iframe heeft geen title-attribuut.', moreInfoNl: 'Iframes worden gebruikt om externe inhoud in te bedden, zoals video\'s, kaarten of formulieren. Zonder een title-attribuut weet hulpsoftware niet wat er in het iframe zit en kondigt het alleen aan als "frame".\n\nGeef elk iframe een title-attribuut dat de inhoud beschrijft (bijvoorbeeld title="Video over duurzaam bouwen" of title="Google Maps kaart van het gemeentehuis"). De title verschijnt niet visueel maar wel hoorbaar.' },
  { testName: 'VideoMissingTitleAriaTest', titleNl: 'Video mist een toegankelijke naam', source: 'html', scs: ['4.1.2'], responsibility: 'content', descriptionNl: 'Een video-element heeft geen aria-label, aria-labelledby of title.', moreInfoNl: 'Bij een video zonder toegankelijke naam kondigt hulpsoftware alleen "video" aan, zonder onderwerp. Voor blinde en slechtziende gebruikers blijft onduidelijk of het de moeite waard is om de video af te spelen.\n\nGeef de video een aria-label dat het onderwerp aangeeft, of voeg een title-attribuut toe. Als er een zichtbare titel boven of bij de video staat, kan aria-labelledby naar dat element wijzen.' },
  { testName: 'IframeIsYouTubeVideoWithKeysDisabledTest', titleNl: 'YouTube-video met sneltoetsen uitgeschakeld', source: 'html', scs: ['2.1.1'], responsibility: 'template', descriptionNl: 'Een ingesloten YouTube-video heeft de parameter disablekb=1 of controls=0 in de URL.', moreInfoNl: 'YouTube-video\'s zijn standaard met het toetsenbord bedienbaar: spatie voor pauze, pijltjes voor terugspoelen, M voor mute. Met disablekb=1 of controls=0 in de embed-URL wordt die bediening uitgeschakeld of zijn de knoppen helemaal weg.\n\nVoor mensen die geen muis kunnen gebruiken is de video dan onbruikbaar. Verwijder deze parameters uit de embed-URL of voeg een eigen toegankelijke bediening toe.' },
  { testName: 'IframeIsVimeoVideoWithKeysDisabledTest', titleNl: 'Vimeo-video met sneltoetsen uitgeschakeld', source: 'html', scs: ['2.1.1'], responsibility: 'template', descriptionNl: 'Een ingesloten Vimeo-video heeft de parameter keyboard=0 in de URL.', moreInfoNl: 'Vimeo-video\'s zijn standaard met het toetsenbord bedienbaar. Met keyboard=0 in de embed-URL wordt die bediening uitgeschakeld.\n\nVoor mensen die geen muis kunnen gebruiken is de video dan onbruikbaar. Verwijder deze parameter uit de embed-URL.' },
  { testName: 'AudioHasAutoplayTest', titleNl: 'Audio speelt automatisch af', source: 'html', scs: ['1.4.2'], responsibility: 'content', descriptionNl: 'Een audio-element heeft het autoplay-attribuut.', moreInfoNl: 'Geluid dat automatisch begint te spelen is hinderlijk voor iedereen, maar vooral voor mensen die een schermlezer gebruiken: het overstemt de voorgelezen tekst en maakt de pagina onbruikbaar.\n\nVerwijder het autoplay-attribuut, of zorg dat de gebruiker het geluid binnen 3 seconden kan stoppen of het volume kan regelen zonder het volume van zijn hele systeem aan te passen.' },
  { testName: 'VideoHasAutoplayTest', titleNl: 'Video speelt automatisch af', source: 'html', scs: ['1.4.2', '2.2.2'], responsibility: 'content', descriptionNl: 'Een video-element heeft het autoplay-attribuut.', moreInfoNl: 'Automatisch afspelende video\'s zijn afleidend voor mensen met cognitieve beperkingen, en als er ook geluid bij zit overstemt het de schermlezer.\n\nVerwijder het autoplay-attribuut. Wil je een visueel effect dat lijkt op autoplay, gebruik dan een silent muted loop met een duidelijke pauze-knop, of bied de gebruiker een knop om de video bewust te starten.' },
  { testName: 'AudioControlsTest', titleNl: 'Audio mist bedieningselementen', source: 'html', scs: ['1.4.2'], responsibility: 'content', descriptionNl: 'Een audio-element heeft geen controls-attribuut.', moreInfoNl: 'Zonder bedieningselementen heeft de gebruiker geen knoppen om de audio te starten, pauzeren of het volume aan te passen. Dat is een blokkade voor iedereen.\n\nVoeg het controls-attribuut toe aan het audio-element, of bouw eigen toegankelijke bedieningsknoppen met JavaScript.' },
  { testName: 'VideoControlsTest', titleNl: 'Video mist bedieningselementen', source: 'html', scs: ['2.1.1'], responsibility: 'template', descriptionNl: 'Een video-element heeft geen controls-attribuut.', moreInfoNl: 'Zonder bedieningselementen kan de gebruiker de video niet pauzeren, terugspoelen of het volume regelen. Voor toetsenbord-gebruikers en mensen die afhankelijk zijn van eigen bedieningssoftware is de video dan onbruikbaar.\n\nVoeg het controls-attribuut toe, of bouw eigen toegankelijke bedieningsknoppen met JavaScript.' },
  { testName: 'ViewportMetaRestrictsScalingTest', titleNl: 'Viewport beperkt zoomen', source: 'html', scs: ['1.4.4', '1.4.10'], responsibility: 'template', descriptionNl: 'De viewport-meta-tag bevat user-scalable=no of een maximum-scale lager dan 2.', moreInfoNl: 'Slechtziende gebruikers en mensen die in fel licht een mobiele website bekijken zoomen vaak in om de tekst groter te maken. Wanneer de viewport-meta-tag zoomen blokkeert, is dat onmogelijk.\n\nVerwijder user-scalable=no en zet maximum-scale op minimaal 2 of laat het weg. De juiste viewport-tag voor toegankelijkheid is meestal: <meta name="viewport" content="width=device-width, initial-scale=1">.' },
  { testName: 'HeadingsAtLeastOneH1Test', titleNl: 'Pagina mist een H1-kop', source: 'html', scs: ['1.3.1', '2.4.6'], responsibility: 'template', descriptionNl: 'De pagina bevat geen H1-kop.', moreInfoNl: 'De H1 is de belangrijkste kop op een pagina en geeft het hoofdonderwerp aan. Hulpsoftware gebruikt de H1 als startpunt: gebruikers springen er direct naartoe om snel te begrijpen waar de pagina over gaat.\n\nZonder H1 ontbreekt dit ankerpunt. De gebruiker moet de hele pagina verkennen om het onderwerp te vinden. Voor mensen met cognitieve beperkingen of voor wie schermlezers gebruikt, kost dat extra moeite.\n\nElke pagina hoort precies één H1 te hebben die de paginatitel weergeeft. De H1 staat meestal bovenaan de hoofdinhoud, niet in de header of de zijbalk.' },
  { testName: 'HeadingEmptyTest', titleNl: 'Lege kop', source: 'html', scs: ['1.3.1', '2.4.6'], responsibility: 'content', descriptionNl: 'De pagina bevat een kop (h1 t/m h6) zonder tekstinhoud.', moreInfoNl: 'Koppen helpen om content op te splitsen en maken het voor bezoekers makkelijker om een pagina te scannen. Ze moeten correct zijn ingesteld zodat bezoekers die schermlezers gebruiken er gebruik van kunnen maken.\n\nEen kop wordt als leeg beschouwd als er geen tekst is die een schermlezer kan voorlezen. Afbeeldingskoppen worden als leeg beschouwd als er geen tekstalternatief beschikbaar is.\n\nIn sommige CMS-editors ontstaan per ongeluk lege koppen — meestal doordat de kop-stijl wordt toegepast op spaties of een lege regel tussen tekst.' },
  { testName: 'HeadingSkipLevelTest', titleNl: 'Kopniveau wordt overgeslagen', source: 'html', scs: ['1.3.1'], responsibility: 'content', descriptionNl: 'De pagina springt van een H-niveau naar een dieper niveau zonder de tussenliggende niveaus te gebruiken.', moreInfoNl: 'Koppen vormen een hiërarchie: H1 voor het hoofdonderwerp, H2 voor secties, H3 voor subsecties, enzovoort. Schermlezer-gebruikers navigeren met sneltoetsen door die hiërarchie en verwachten een logische opbouw.\n\nWanneer een pagina van H2 direct naar H4 springt (H3 overslaand), denkt de gebruiker dat er een sectie is overgeslagen. De structuur wordt verwarrend.\n\nGebruik H-niveaus in oplopende volgorde. Voor visuele opmaak van een kop gebruik je CSS, niet een ander H-niveau.' },
  { testName: 'TableWithHeadingsTest', titleNl: 'Tabel met kopcellen', source: 'html', scs: ['1.3.1'], responsibility: 'content', descriptionNl: 'De tabel heeft kopcellen die niet als th-element zijn gemarkeerd.', moreInfoNl: 'In een data-tabel zijn er gewone cellen (td) en kopcellen (th). De th-elementen vertellen hulpsoftware welke kolom of rij ergens bij hoort. Bij een tabel met financiële cijfers leest een schermlezer dan bijvoorbeeld "kolom Jaar, rij 2024: 1500 euro".\n\nWanneer kopcellen visueel wel zijn opgemaakt (vetgedrukt, andere achtergrond) maar in HTML als td staan, mist deze koppeling. De gebruiker hoort alleen losse getallen zonder context.\n\nMaak van elke kopcel een th-element. Voeg ook scope="col" of scope="row" toe om expliciet aan te geven of het een kolom- of rijkop is.' },
  { testName: 'TableWithoutHeadersTest', titleNl: 'Tabel zonder kopcellen', source: 'html', scs: ['1.3.1'], responsibility: 'content', descriptionNl: 'De tabel bevat data maar heeft geen enkele th-cel.', moreInfoNl: 'Een data-tabel zonder kopcellen is voor schermlezers een verzameling losse getallen of woorden zonder duidelijke samenhang. De gebruiker kan niet weten waar een cel bij hoort.\n\nVoeg th-elementen toe voor de koppen van de kolommen of rijen. Gebruikt de tabel alleen voor visuele opmaak (geen echte data), overweeg dan om hem te vervangen door divs met CSS.' },
  { testName: 'TableCellMissingContextTest', titleNl: 'Tabelcel mist context', source: 'html', scs: ['1.3.1'], responsibility: 'content', descriptionNl: 'Een datacel in een tabel met zowel rij- als kolomkoppen mist de koppeling naar de bijbehorende kopcellen.', moreInfoNl: 'In een tabel met meerdere dimensies (kolomkoppen én rijkoppen) is het voor schermlezer-gebruikers cruciaal dat elke datacel weet bij welke kop hij hoort. Bij een tabel met cijfers per jaar én per kwartaal moet de gebruiker horen "Kwartaal 2, 2024: 1500 euro".\n\nZonder scope-attributen op de th-cellen of headers-attributen op de td-cellen mist die koppeling. De gebruiker hoort dan alleen losse cijfers.\n\nLos op door scope="col" of scope="row" toe te voegen aan elke th, of door headers-attributen op td-cellen die verwijzen naar de id van de relevante th.' },
  { testName: 'EmptyContainerTest', titleNl: 'Container-element is leeg', source: 'html', scs: ['1.3.1'], responsibility: 'template', descriptionNl: 'Een structureel element zoals section, article, nav of main bevat geen inhoud.', moreInfoNl: 'Structurele HTML-elementen geven betekenis aan de pagina-indeling. Een nav-element vertelt hulpsoftware "hier zit de navigatie", een main-element "hier begint de hoofdinhoud". Schermlezer-gebruikers gebruiken die landmarks om snel door de pagina te springen.\n\nWanneer zo\'n element leeg is, klopt de aangekondigde structuur niet meer. Een gebruiker springt naar "navigatie" en vindt niets. Vaak ontstaat dit door dynamische scripts die de inhoud niet (meer) vullen, of door overgebleven template-resten.\n\nVerwijder lege structuur-elementen, of zorg dat ze daadwerkelijk inhoud bevatten die past bij hun rol.' },
  { testName: 'TableHeaderCellMissingHeaderRoleTest', titleNl: 'Tabelkop-cel mist een kopcel-rol', source: 'browser', scs: ['1.3.1'], responsibility: 'content', descriptionNl: 'Een cel die er door styling als kopcel uitziet, staat in HTML als gewone td-cel.', moreInfoNl: 'Soms wordt een cel visueel opgemaakt als kop (vetgedrukt, andere achtergrond) maar blijft hij een gewone td in de HTML. Voor zienden ziet het er goed uit, maar hulpsoftware weet niet dat het een kop is en behandelt het als data.\n\nDeze test draait in de echte browser en vergelijkt computed CSS-styling van cellen binnen dezelfde rij. Verdachte signalen: vetgedrukte tekst, andere achtergrondkleur, of de positie eerste-cel-van-rij. Bij twee of meer signalen wordt de cel geflagd.\n\nHet gevolg van ontbrekende kopcel-rol: de tabelstructuur klopt niet voor schermlezer-gebruikers en er wordt niet de juiste context bij de datacellen voorgelezen.\n\nMaak van een visuele kopcel een th-element of voeg role="columnheader"/"rowheader" toe. Visuele opmaak hoort altijd CSS te zijn, niet een keuze tussen td en th.' },
  { testName: 'AllRolesInvalidTest', titleNl: 'Alle rollen zijn ongeldig', source: 'html', scs: ['1.3.1', '4.1.2'], responsibility: 'template', descriptionNl: 'Een element heeft een role-attribuut met uitsluitend rollen die geen geldige ARIA-rollen zijn.', moreInfoNl: 'ARIA-rollen vertellen hulpsoftware welk type element het is (button, navigation, dialog). Wanneer een ontwikkelaar een typo maakt of een verouderde rol gebruikt, herkent hulpsoftware de rol niet en valt terug op de standaard.\n\nVoorbeelden van veelvoorkomende fouten: role="buton" (typo), role="menu-item" (moet menuitem zonder streep), role="container" (bestaat niet).\n\nControleer de gebruikte role-waardes tegen de officiële ARIA-specificatie. In veel gevallen is een native HTML-element (button, nav, dialog) beter dan een ARIA-rol op een div.' },
  { testName: 'IncorrectTableHeaderReferenceTest', titleNl: 'Er wordt niet correct naar tabelkoppen verwezen', source: 'html', scs: ['1.3.1'], responsibility: 'content', descriptionNl: 'Een cel met headers-attribuut verwijst naar een id die niet in de tabel bestaat.', moreInfoNl: 'Het headers-attribuut op een td-cel koppelt deze expliciet aan een of meer th-cellen via hun id. Wanneer een verwijzing naar een niet-bestaande id wijst, faalt de koppeling: hulpsoftware leest geen kop voor bij de datacel.\n\nDit komt vaak door typo\'s in de id of headers-attribuutwaarde, of door later verwijderde th-cellen waarvan de verwijzing in td\'s is blijven staan.\n\nControleer of elke id in een headers-attribuut overeenkomt met een bestaande id in de tabel. Een betere oplossing is vaak scope="col"/"row" op de th-cellen zelf in plaats van handmatige id-koppeling.' },
  { testName: 'FormMissingLabelsTest', titleNl: 'Formulier mist labels', source: 'html', scs: ['1.3.1', '3.3.2', '4.1.2'], responsibility: 'mixed', descriptionNl: 'Een formulier bevat invoervelden waar geen label aan gekoppeld is.', moreInfoNl: 'Een label vertelt de gebruiker wat hij moet invullen in een veld. Voor schermlezer-gebruikers is dit cruciaal: zonder label hoort hij alleen "tekstveld" en weet hij niet of het om een naam, e-mailadres of postcode gaat.\n\nKoppel elk invoerveld aan een label via for-attribuut (<label for="naam">Naam</label> + <input id="naam">) of door de input binnen de label te zetten.\n\nEen placeholder-tekst is geen vervanging voor een label: die verdwijnt zodra de gebruiker begint te typen en is voor sommige hulpsoftware niet leesbaar.' },
  { testName: 'InputMissingLabelTest', titleNl: 'Invoerveld mist een label', source: 'html', scs: ['1.3.1', '3.3.2', '4.1.2'], responsibility: 'mixed', descriptionNl: 'Een specifiek invoerveld heeft geen label, aria-label, aria-labelledby of title.', moreInfoNl: 'Per invoerveld checkt deze test of het veld een toegankelijke naam heeft. Een schermlezer kondigt de input dan aan met die naam ("tekstveld, Voornaam").\n\nDe test slaat honeypot-velden over (anti-spam-velden met tabindex="-1", type="hidden" of binnen een verborgen container) — die zijn bewust niet zichtbaar voor gebruikers en horen niet bij WCAG-toetsing.\n\nVoor zichtbare velden: voeg een label toe, of als dat visueel niet kan een aria-label of aria-labelledby.' },
  { testName: 'FormMissingFieldsetTest', titleNl: 'Formulier mist een fieldset', source: 'html', scs: ['1.3.1'], responsibility: 'template', descriptionNl: 'Een groep gerelateerde invoervelden (zoals radio-knoppen) staat niet binnen een fieldset met een legend.', moreInfoNl: 'Bij een groep keuzes (bijvoorbeeld radio-knoppen "Ja / Nee" voor de vraag "Wilt u nieuwsbrief?") moet hulpsoftware niet alleen het label van elke knop weten, maar ook de gemeenschappelijke vraag.\n\nDe HTML-manier is om de groep in een <fieldset> te zetten met een <legend> die de vraag bevat. Schermlezers kondigen de legend aan bij elke radio-knop in de groep.\n\nZonder fieldset hoort de gebruiker alleen "Ja" en "Nee" zonder de vraag. Vooral problematisch bij meerdere groepen achter elkaar.' },
  { testName: 'StrongHasMoreThanFourWordsTest', titleNl: 'Veel woorden in strong-element', source: 'html', scs: ['1.3.1'], responsibility: 'content', note: 'oneigenlijk gebruik strong', descriptionNl: 'Een strong-element bevat meer dan vier woorden.', moreInfoNl: 'Het strong-element is bedoeld voor sterke nadruk op enkele woorden — vergelijkbaar met hoe je in spraak een woord extra accent geeft. Hulpsoftware kondigt strong-tekst soms aan ("met nadruk: belangrijk") of leest het in een andere toonzetting voor.\n\nLange teksten in strong (zoals hele zinnen of alinea\'s) zijn meestal bedoeld voor visuele opmaak — vetgedrukt om de aandacht te trekken. Dat is oneigenlijk: hulpsoftware geeft elke zin een opvallende nadruk en de bedoelde betekenis vervaagt.\n\nGebruik CSS (font-weight: bold) voor visuele opmaak. Reserveer strong voor woorden waar echt extra betekenis op moet liggen.' },
  { testName: 'ElementsStyledWithStrongOrEmTest', titleNl: 'Strong of em gebruikt voor opmaak', source: 'html', scs: ['1.3.1'], responsibility: 'content', note: 'visuele opmaak met strong/em', descriptionNl: 'Strong of em wordt gebruikt op tekst die visueel opvallend moet zijn, zonder dat de tekst inhoudelijk nadruk verdient.', moreInfoNl: 'Strong betekent "sterke nadruk", em betekent "klemtoon". Beide hebben een betekenis voor hulpsoftware: een schermlezer kan de toon aanpassen of het woord aankondigen als "met nadruk".\n\nVeel websites gebruiken deze elementen onbedoeld voor visuele opmaak — bijvoorbeeld op titels, labels of namen die alleen vetgedrukt of cursief moeten staan. Voor schermlezer-gebruikers klinkt dat oneigenlijk en verwarrend.\n\nGebruik CSS (font-weight, font-style) voor visuele opmaak. Reserveer strong en em voor inhoudelijke nadruk.' },
  { testName: 'SkipLinkTest', titleNl: 'Skip-link aanwezig', source: 'html', scs: ['2.4.1'], responsibility: 'template', descriptionNl: 'De pagina mist een "Direct naar de inhoud"-link bovenaan voor toetsenbord-gebruikers.', moreInfoNl: 'Een skip-link is een verborgen link die als eerste focusbaar element op de pagina staat. Wanneer een toetsenbord-gebruiker op Tab drukt, verschijnt deze link en kan hij direct naar de hoofdinhoud springen.\n\nZonder skip-link moeten toetsenbord-gebruikers bij elke pagina door de hele navigatie tabben voordat ze bij de inhoud zijn. Voor mensen met motorische beperkingen kost dat veel moeite.\n\nVoeg bovenaan de pagina een link toe naar de main-id (bijvoorbeeld <a href="#main">Direct naar de inhoud</a>). Met CSS kun je hem visueel verbergen totdat hij focus krijgt.' },
  { testName: 'AriaLandmarksTest', titleNl: 'Landmarks zonder unieke naam', source: 'html', scs: ['2.4.1', '4.1.2'], responsibility: 'template', note: 'SIA-R56', descriptionNl: 'De pagina heeft meerdere landmarks van hetzelfde type zonder onderscheidende namen.', moreInfoNl: 'Landmarks zijn structuur-elementen zoals header, nav, main en footer. Hulpsoftware gebruikt ze om snel door de pagina te springen. Een blinde gebruiker kan met een sneltoets bijvoorbeeld direct naar "main" om de inhoud te bereiken.\n\nAls dezelfde rol meerdere keren op de pagina voorkomt (bijvoorbeeld twee header-elementen of drie nav-elementen) moet elk een eigen naam hebben. Zonder die namen hoort de gebruiker alleen "banner, banner" of "navigatie, navigatie, navigatie" en kan niet kiezen.\n\nDe naam komt uit aria-label of aria-labelledby. Bijvoorbeeld: aria-label="Site" op de hoofd-header en aria-label="Hoofdmenu" op de eerste nav, aria-label="Kruimelpad" op de tweede.\n\nDeze regel staat ook bekend als SIA-R56 in de auditmethodiek van de Stichting Inclusieve Auditpraktijk.' },
  { testName: 'LinkWithoutTextTest', titleNl: 'Link zonder tekst', source: 'html', scs: ['2.4.4', '4.1.2'], responsibility: 'content', descriptionNl: 'Een link heeft geen zichtbare tekst en ook geen toegankelijke naam via aria-label of aria-labelledby.', moreInfoNl: 'Hulpsoftware kondigt zo\'n link alleen aan als "link" of leest de href voor — onbruikbaar. Voor blinde en slechtziende gebruikers blijft de bestemming onduidelijk.\n\nGeef de link een betekenisvolle naam. Dat kan via zichtbare tekst, een aria-label, of door inhoud (bv. een afbeelding met passende alt-tekst) die de bestemming beschrijft.' },
  { testName: 'EmptyLinkTest', titleNl: 'Lege link', source: 'html', scs: ['2.4.4', '4.1.2'], responsibility: 'content', descriptionNl: 'Een link bevat geen inhoud — geen tekst, geen afbeelding, niets.', moreInfoNl: 'Een volledig lege link is een onverwacht obstakel: toetsenbord-gebruikers kunnen hem tabben en activeren, maar weten niet wat er gebeurt. Schermlezers kondigen alleen "link" aan.\n\nVoeg betekenisvolle inhoud toe of verwijder de link. Lege links ontstaan vaak per ongeluk in CMS-editors of door dynamische scripts die de inhoud niet vullen.' },
  { testName: 'LinkMissingHrefTest', titleNl: 'Link mist een href of heeft placeholder', source: 'html', scs: ['2.1.1', '2.4.4'], responsibility: 'content', descriptionNl: 'Een link heeft geen href-attribuut of gebruikt een placeholder zoals "#", "/#" of "javascript:void(0)".', moreInfoNl: 'Zonder een geldige href is een element technisch geen link. Browsers behandelen het anders: geen Tab-focus, geen rechtermuisknop-menu om in nieuw tabblad te openen, geen verwijzing in de statusbalk.\n\nVoor screenreader-gebruikers kondigt hulpsoftware het mogelijk wel als link aan maar er gebeurt niets bij activeren. Verwarrend en onbruikbaar.\n\nGebruik een echte URL in href. Heb je iets nodig dat alleen JavaScript triggert, gebruik dan een button-element in plaats van een a-tag.\n\nUitzondering: tel:- en mailto:-links met placeholder zijn geen WCAG-falen — die werken via een ander mechanisme.' },
  { testName: 'PageContainsLinkReadMoreTest', titleNl: 'Link met tekst "Lees meer"', source: 'html', scs: ['2.4.4'], responsibility: 'content', descriptionNl: 'De pagina bevat links met algemene teksten als "lees meer", "klik hier" of "meer".', moreInfoNl: 'Schermlezer-gebruikers kunnen op een pagina een lijst van alle links opvragen om snel een overzicht te krijgen. In die lijst zien ze alleen de linktekst, zonder de omringende context.\n\nLinken als "lees meer" en "klik hier" zijn dan betekenisloos: tien keer "lees meer" zonder onderscheid. De gebruiker moet teruglopen naar de bron om context te vinden.\n\nMaak elke linktekst zelfstandig betekenisvol. Bijvoorbeeld in plaats van "Lees meer over de nieuwsbrief" gewoon: "Meer over de nieuwsbrief" als linktekst.' },
  { testName: 'PageContainsMultipleSameLinksTest', titleNl: 'Meerdere links naar dezelfde pagina met verschillende tekst', source: 'html', scs: ['2.4.4'], responsibility: 'content', note: 'hoge false-positive rate', descriptionNl: 'Meerdere links op dezelfde pagina wijzen naar dezelfde URL maar gebruiken verschillende linkteksten.', moreInfoNl: 'Wanneer linkteksten verschillen voor dezelfde bestemming, kan dat verwarrend zijn: de gebruiker denkt dat hij naar een andere pagina gaat dan in werkelijkheid.\n\nLet op: deze test heeft een hoge false-positive rate. Vaak zijn meerdere links naar dezelfde pagina prima — bijvoorbeeld een knop in de header en een uitgebreide tekst in de inhoud die naar het contactformulier verwijzen.\n\nBeoordeel handmatig: zijn de linkteksten misleidend over de bestemming? Alleen dan is het een echt probleem. Bij heldere context (zoals "contact" in de header en "Neem contact op" in de tekst) is het geen WCAG-falen.' },
  { testName: 'ButtonEmptyTest', titleNl: 'Lege knop', source: 'html', scs: ['4.1.2'], responsibility: 'content', descriptionNl: 'Een button-element heeft geen tekst, geen aria-label, geen aria-labelledby en geen afbeelding met alt.', moreInfoNl: 'Een knop zonder toegankelijke naam is voor schermlezer-gebruikers volledig onbruikbaar. Ze horen "knop" maar weten niet wat hij doet.\n\nGeef elke knop een naam. Voor tekst-knoppen: zorg dat de tekst direct in de button staat. Voor icon-knoppen: voeg een aria-label toe met de actie ("Zoeken", "Menu sluiten", "Cookie-instellingen openen").' },
  { testName: 'IframeIsHCaptchaTest', titleNl: 'hCaptcha aanwezig', source: 'html', scs: ['3.3.7'], responsibility: 'template', note: 'CAPTCHA-detectie', descriptionNl: 'De pagina bevat een hCaptcha-iframe.', moreInfoNl: 'CAPTCHA\'s zijn voor veel mensen met handicaps een groot probleem. Visuele puzzels (klik op alle stoplichten) zijn onmogelijk voor blinden, en audio-alternatieven zijn vaak slecht te verstaan. Cognitief vereisen ze begrip dat niet iedereen heeft.\n\nDeze test detecteert puur dat een CAPTCHA aanwezig is. Beoordeel handmatig of er een toegankelijk alternatief is, of vervang het door een niet-CAPTCHA-oplossing (rate limiting, honeypot-velden, server-side detectie).' },
  { testName: 'ImplicitlyHiddenWithFocusableContentTest', titleNl: 'Container met inert bevat focusbare elementen', source: 'html', scs: ['4.1.2'], responsibility: 'template', descriptionNl: 'Een element met het inert-attribuut bevat focusbare kinderen die hulpsoftware wel ziet.', moreInfoNl: 'Het inert-attribuut maakt een element en al zijn nakomelingen volledig onbereikbaar voor toetsenbord-focus, muiskliks en hulpsoftware. Het wordt gebruikt om delen van een pagina tijdelijk uit te schakelen, bijvoorbeeld achter een open modal.\n\nWanneer een container inert is maar er staan toch focusbare elementen in (links, knoppen, invoervelden), is dat verdacht. Browsers volgen inert correct, maar oudere browsers of onverwachte JavaScript-interacties kunnen tot inconsistent gedrag leiden.\n\nVerwijder inert wanneer de inhoud bedoeld is om bereikbaar te zijn, of zorg dat focusbare kinderen ook expliciet uitgeschakeld zijn (tabindex="-1", disabled-attribuut).' },
  { testName: 'DetailsSummaryMissingNameTest', titleNl: 'Uitklap-element heeft geen toegankelijke naam', source: 'html', scs: ['4.1.2'], responsibility: 'content', descriptionNl: 'Een details-element heeft een summary zonder tekst, aria-label of title.', moreInfoNl: 'Het details/summary-patroon is de native HTML-manier om een uitklap-widget te maken. De summary dient als knop die het paneel opent en sluit. Zonder tekst of toegankelijke naam weet de gebruiker niet wat er gaat openen.\n\nSchermlezer-gebruikers horen "knop, samengevouwen" zonder context. Voor blinde en slechtziende gebruikers is het widget daardoor onbruikbaar.\n\nGeef de summary altijd betekenisvolle tekst die het onderwerp van het uitklapbare paneel beschrijft (bijvoorbeeld "Veelgestelde vragen over parkeren").' },
  { testName: 'DuplicateIframeTitleTest', titleNl: 'Meerdere iframes met dezelfde titel', source: 'html', scs: ['4.1.2'], responsibility: 'content', descriptionNl: 'Twee of meer iframes op de pagina hebben dezelfde title-tekst.', moreInfoNl: 'Wanneer meerdere iframes dezelfde title hebben, kan een schermlezer-gebruiker ze niet uit elkaar houden. Bij drie video-iframes met title="Video" hoort de gebruiker drie keer hetzelfde — onmogelijk om de juiste te kiezen.\n\nGeef elk iframe een unieke, beschrijvende title die de inhoud weergeeft. Bijvoorbeeld: "Video over duurzaam bouwen", "Video over afval scheiden", "Video over openingstijden".' },
  { testName: 'MenuItemMissingNameTest', titleNl: 'Menu-item mist een toegankelijke naam', source: 'html', scs: ['4.1.2'], responsibility: 'template', descriptionNl: 'Een element met role="menuitem", "menuitemcheckbox" of "menuitemradio" heeft geen toegankelijke naam.', moreInfoNl: 'Menu-items in een ARIA-menu (zoals een hamburger-menu of dropdown-menu met role="menu") moeten elk een naam hebben zodat schermlezer-gebruikers weten welke optie ze kiezen.\n\nWanneer een menu-item geen tekst, aria-label of aria-labelledby heeft, hoort de gebruiker alleen "menu-item, menu-item, menu-item" zonder onderscheid. Vaak ontstaat dit bij iconisch-menu\'s waar het label visueel naast de knop staat maar niet aan het element gekoppeld is.\n\nVoeg de tekst van de actie direct in het element toe, of gebruik aria-label op het menu-item zelf. Bijvoorbeeld aria-label="Sluit menu" op een kruisknop, of "Naar contact" op een navigatie-item.' },
  { testName: 'HiddenWithFocusableContentTest', titleNl: 'Verborgen element heeft focusbare content', source: 'browser', scs: ['4.1.2'], responsibility: 'template', descriptionNl: 'Een container met aria-hidden="true" of display:none bevat toch focusbare elementen.', moreInfoNl: 'Schermlezers slaan elementen met aria-hidden="true" en display:none over. Maar als zo\'n container focusbare elementen (links, knoppen, invoervelden) bevat, krijgen die wél focus bij Tab-navigatie. De gebruiker krijgt focus op een element dat hulpsoftware niet aankondigt — verwarrend en niet bruikbaar.\n\nLos op door óf de container echt te verbergen (ook focus uitsluiten met tabindex="-1" of inert), óf de aria-hidden te verwijderen als de inhoud bereikbaar moet zijn.' },
  { testName: 'AriaRoleInvalidContextTest', titleNl: 'ARIA-rol niet binnen de vereiste context', source: 'html', scs: ['1.3.1'], responsibility: 'template', descriptionNl: 'Een ARIA-rol staat niet binnen het verplichte ouder-element.', moreInfoNl: 'Sommige ARIA-rollen vereisen een specifieke parent. Een role="tab" hoort binnen een role="tablist" te staan, een role="menuitem" binnen een role="menu". Zonder die context kan hulpsoftware de structuur niet correct interpreteren en wordt navigatie verbroken.\n\nControleer of elke ARIA-rol in de juiste structuur is genest, of vervang de rollen door semantisch HTML waar dat kan.' },
  { testName: 'AriaRequiredAttrTest', titleNl: 'Vereist ARIA-attribuut ontbreekt', source: 'html', scs: ['4.1.2'], responsibility: 'template', descriptionNl: 'Een element met een ARIA-rol mist een attribuut dat voor die rol verplicht is.', moreInfoNl: 'Sommige ARIA-rollen verplichten extra attributen. Een role="slider" vereist aria-valuenow zodat hulpsoftware de huidige waarde kan voorlezen. Een role="checkbox" vereist aria-checked om de aan/uit-status door te geven.\n\nZonder deze attributen krijgt de gebruiker incomplete informatie en kan de interactie mislukken. Voeg de ontbrekende attributen toe of vervang de ARIA-rol door een native HTML-element dat hetzelfde gedrag uit zichzelf heeft.' },
  { testName: 'AriaAttributeNotSupportedTest', titleNl: 'ARIA-attribuut niet ondersteund op dit element', source: 'html', scs: ['4.1.2'], responsibility: 'template', descriptionNl: 'Een ARIA-attribuut staat op een element waar dat attribuut niet hoort.', moreInfoNl: 'ARIA-attributen zijn rol-specifiek. aria-checked werkt alleen op elementen met de rol checkbox, radio, switch of menuitemcheckbox. Op een gewone span of div heeft het geen effect — hulpsoftware negeert het of geeft fouten.\n\nControleer of het element de juiste rol heeft, of verwijder het attribuut. Veel issues ontstaan door copy-paste van ARIA-patronen die niet bij het gebruikte element passen.' },
  { testName: 'MissingStatusOrPropertyTest', titleNl: 'Status of eigenschap ontbreekt', source: 'html', scs: ['4.1.2'], responsibility: 'template', descriptionNl: 'Een interactief element mist een status- of eigenschap-attribuut dat de huidige toestand aangeeft.', moreInfoNl: 'Toggle-knoppen (uitklap, accordeon, dropdown) moeten hun open/dicht-status aan hulpsoftware doorgeven via aria-expanded of aria-pressed. Een knop met aria-controls hoort ook aria-expanded te hebben — dat is het standaardpatroon voor disclosure-widgets.\n\nZonder deze attributen weet een schermlezer-gebruiker niet of een menu open of dicht staat, of een knop ingedrukt is. Voeg het juiste status-attribuut toe en update het bij iedere interactie via JavaScript.' },

  // ---- Browser-tests (browser-tests.ts) ----
  { testName: 'ColorContrastTest', titleNl: 'Kleurcontrast voldoet niet aan de minimale eis', source: 'browser', scs: ['1.4.3'], responsibility: 'ontwerp', descriptionNl: 'Tekst op de pagina heeft te weinig contrast met de achtergrond.', moreInfoNl: 'Slechtziende gebruikers en mensen met kleurperceptieproblemen zien tekst met onvoldoende contrast moeilijk of niet. Ook gebruikers van een telefoon in fel zonlicht hebben last van te lage contrasten.\n\nWCAG 2.1 stelt eisen aan de contrastverhouding tussen tekst en de achtergrond:\n- Normale tekst (kleiner dan 18pt of kleiner dan 14pt bold): minimaal 4,5:1\n- Grote tekst (vanaf 18pt of vanaf 14pt bold): minimaal 3:1\n\nDe contrastverhouding wordt berekend uit de helderheid van de tekstkleur en de achtergrondkleur. Bij decoratieve tekst en logos geldt de eis niet.\n\nLet op dat de test niet betrouwbaar kan oordelen bij tekst op een achtergrondafbeelding (bijvoorbeeld witte tekst boven een hero-foto). Beoordeel die gevallen handmatig.' },
  { testName: 'LabelInNameTest', titleNl: 'Zichtbare label komt niet overeen met toegankelijke naam', source: 'browser', scs: ['2.5.3'], responsibility: 'template', descriptionNl: 'De zichtbare tekst op een knop of link komt niet overeen met de naam die hulpsoftware voorleest.', moreInfoNl: 'Mensen die de website bedienen met spraakbesturing (bijvoorbeeld iemand met een motorische beperking) zeggen de zichtbare tekst van een knop om die te activeren. Bijvoorbeeld "klik op zoeken".\n\nAls de toegankelijke naam (uit aria-label of aria-labelledby) afwijkt van de zichtbare tekst, werkt het commando niet. De gebruiker zou het Engelse "search" moeten zeggen terwijl op de knop "Zoeken" staat.\n\nDe regel is: de zichtbare tekst moet (volledig en in dezelfde volgorde) voorkomen in de toegankelijke naam. Uitbreiding mag wel — bijvoorbeeld zichtbaar "NL" met aria-label "NL, Nederlandse versie" is goed. Vervanging niet — aria-label "Nederlandse versie" zonder "NL" erin breekt de regel.' },
  { testName: 'AutoRefreshTest', titleNl: 'Pagina vernieuwt of stuurt door zonder waarschuwing', source: 'browser', scs: ['2.2.1', '2.2.4', '3.2.5'], responsibility: 'template', descriptionNl: 'De pagina ververst automatisch of stuurt door naar een andere URL zonder dat de gebruiker dit kan stoppen.', moreInfoNl: 'Tijdslimieten op een pagina (zoals een meta-refresh die de pagina elke 60 seconden ververst) leveren problemen voor gebruikers die meer tijd nodig hebben om content te lezen of een formulier in te vullen. Voor mensen die schermlezers gebruiken kan een automatische verversing ook hun cursorpositie wegvagen.\n\nWCAG 2.2.1 eist dat de gebruiker de tijdslimiet kan uitschakelen, verlengen of aanpassen. Uitzonderingen zijn een limiet van meer dan 20 uur of een real-time gebeurtenis (zoals een live veiling).\n\nServer-side HTTP-redirects (status 3xx) vallen technisch niet onder 2.2.1, omdat ze geen tijdslimiet zijn maar een directe doorverwijzing. Ze kunnen wel wijzen op verouderde URL-structuur en verbroken interne links.' },
];

/** Alle WCAG 2.2 A + AA criteria — bron-of-truth lijst */
export const ALL_AA_SCS = [
  '1.1.1',
  '1.2.1', '1.2.2', '1.2.3', '1.2.4', '1.2.5',
  '1.3.1', '1.3.2', '1.3.3', '1.3.4', '1.3.5',
  '1.4.1', '1.4.2', '1.4.3', '1.4.4', '1.4.5', '1.4.10', '1.4.11', '1.4.12', '1.4.13',
  '2.1.1', '2.1.2', '2.1.4',
  '2.2.1', '2.2.2',
  '2.3.1',
  '2.4.1', '2.4.2', '2.4.3', '2.4.4', '2.4.5', '2.4.6', '2.4.7', '2.4.11',
  '2.5.1', '2.5.2', '2.5.3', '2.5.4', '2.5.7', '2.5.8',
  '3.1.1', '3.1.2',
  '3.2.1', '3.2.2', '3.2.3', '3.2.4', '3.2.6',
  '3.3.1', '3.3.2', '3.3.3', '3.3.4', '3.3.7', '3.3.8',
  '4.1.2', '4.1.3',
];

/** Geef alle tests die een specifieke SC raken. */
export function getTestsForSC(sc: string): TestCoverage[] {
  return TEST_COVERAGE.filter((t) => t.scs.includes(sc));
}

/** Mapping van testName naar SCs die hij raakt — voor reverse lookup. */
export function getSCsForTest(testName: string): string[] {
  const entry = TEST_COVERAGE.find((t) => t.testName === testName);
  return entry?.scs || [];
}
